// Тексты страниц под ниши (/cafe/, /beauty-salon/, /shop/ и их версии /ru/…, /uk/…, /sk/…).
// Собираются скриптом scripts/build-seo.js по шаблону scripts/niche.template.html.
module.exports = {
  cafe: {
    slug: 'cafe',
    icon: '☕',
    ru: {
      name: 'Для кафе и кофеен',
      metaTitle: 'Программа лояльности для кафе и кофейни — Loya',
      metaDesc: 'Электронная штамп-карта «каждый 10-й кофе бесплатно», сканер в телефоне бариста, автоматические рассылки и аналитика для кафе, кофеен и пекарен. 14 дней бесплатно.',
      h1: 'Программа лояльности', h1gold: 'для кафе и кофеен',
      lead: 'Электронная штамп-карта вместо бумажной: гость показывает QR, бариста сканирует его телефоном — и через неделю гость возвращается за следующей чашкой.',
      painsTitle: 'Знакомо?',
      pains: [
        ['🧾', 'Бумажные карточки теряются', 'Гости забывают карточки дома, а штампы легко подделать. Вы не знаете, кто ваш постоянный клиент.'],
        ['🕒', 'Пустые утренние и дневные часы', 'В час пик очередь, а после обеда пусто. Нечем позвать гостей в тихое время.'],
        ['👋', 'Новые гости не возвращаются', 'Человек зашёл один раз — и пропал. Связаться с ним уже нельзя.'],
      ],
      howTitle: 'Как Loya помогает кафе',
      how: [
        ['☕', 'Штамп-карта «10-й кофе бесплатно»', 'Настраивается за минуту: сколько штампов, какой подарок. Подарок система отмечает сама.'],
        ['📱', 'Телефон бариста — сканер', 'Откройте QR на экране кассы — телефон становится беспроводным сканером. Отметка за 2 секунды, очередь не растёт.'],
        ['⏰', 'Двойные штампы в тихие часы', 'Включите акцию на 14:00–17:00 — и гости сами начнут приходить в пустое время.'],
        ['💌', 'Автоматические письма', 'Гостю, который в шаге от подарка, пропал на месяц или празднует день рождения, письмо уходит само.'],
      ],
      exampleTitle: 'Пример',
      example: 'Кофейня на 600 гостей в месяц. Если с картой лояльности хотя бы 10% из них зайдут ещё по одному разу при среднем чеке €4, это около €240 дополнительной выручки в месяц — в 24 раза больше цены подписки.',
      faq: [
        ['Нужен ли гостю отдельное приложение?', 'Нет. Карта открывается по ссылке или QR и сохраняется в Google Wallet или Telegram. Можно и напечатать пластиковую карту с QR.'],
        ['Нужен ли специальный сканер?', 'Нет — подойдёт телефон любого сотрудника. Если у вас есть USB-сканер штрихкодов, он тоже работает.'],
        ['Подойдёт ли для пекарни или небольшой сети?', 'Да. Для нескольких точек есть тариф Pro: общая база, аналитика по каждой точке, сотрудники и роли.'],
      ],
    },
    uk: {
      name: 'Для кафе та кав’ярень',
      metaTitle: 'Програма лояльності для кафе та кав’ярні — Loya',
      metaDesc: 'Електронна штамп-картка «кожна 10-та кава безкоштовно», сканер у телефоні бариста, автоматичні розсилки й аналітика для кафе, кав’ярень і пекарень. 14 днів безкоштовно.',
      h1: 'Програма лояльності', h1gold: 'для кафе та кав’ярень',
      lead: 'Електронна штамп-картка замість паперової: гість показує QR, бариста сканує його телефоном — і за тиждень гість повертається по наступну чашку.',
      painsTitle: 'Знайомо?',
      pains: [
        ['🧾', 'Паперові картки губляться', 'Гості забувають картки вдома, а штампи легко підробити. Ви не знаєте, хто ваш постійний клієнт.'],
        ['🕒', 'Порожні ранкові й денні години', 'У годину пік черга, а після обіду порожньо. Нічим покликати гостей у тихий час.'],
        ['👋', 'Нові гості не повертаються', 'Людина зайшла один раз — і зникла. Зв’язатися з нею вже не можна.'],
      ],
      howTitle: 'Як Loya допомагає кафе',
      how: [
        ['☕', 'Штамп-картка «10-та кава безкоштовно»', 'Налаштовується за хвилину: скільки штампів, який подарунок. Подарунок система позначає сама.'],
        ['📱', 'Телефон бариста — сканер', 'Відкрийте QR на екрані каси — телефон стає бездротовим сканером. Позначка за 2 секунди, черга не росте.'],
        ['⏰', 'Подвійні штампи в тихі години', 'Увімкніть акцію на 14:00–17:00 — і гості самі почнуть приходити в порожній час.'],
        ['💌', 'Автоматичні листи', 'Гостю, якому лишився крок до подарунка, який зник на місяць або святкує день народження, лист іде сам.'],
      ],
      exampleTitle: 'Приклад',
      example: 'Кав’ярня на 600 гостей на місяць. Якщо з карткою лояльності хоча б 10% із них зайдуть ще по разу при середньому чеку €4, це близько €240 додаткової виручки на місяць — у 24 рази більше за ціну підписки.',
      faq: [
        ['Чи потрібен гостю окремий застосунок?', 'Ні. Картка відкривається за посиланням або QR і зберігається в Google Wallet чи Telegram. Можна й надрукувати пластикову картку з QR.'],
        ['Чи потрібен спеціальний сканер?', 'Ні — підійде телефон будь-якого працівника. Якщо у вас є USB-сканер штрихкодів, він теж працює.'],
        ['Чи підійде для пекарні або невеликої мережі?', 'Так. Для кількох точок є тариф Pro: спільна база, аналітика по кожній точці, працівники й ролі.'],
      ],
    },
    sk: {
      name: 'Pre kaviarne a kafé',
      metaTitle: 'Vernostný program pre kaviareň a kafé — Loya',
      metaDesc: 'Digitálna pečiatková karta „každá 10. káva zadarmo“, skener v telefóne baristu, automatické e-maily a analytika pre kaviarne, kafé a pekárne. 14 dní zadarmo.',
      h1: 'Vernostný program', h1gold: 'pre kaviarne a kafé',
      lead: 'Digitálna pečiatková karta namiesto papierovej: hosť ukáže QR, barista ho naskenuje telefónom — a o týždeň sa hosť vráti na ďalšiu šálku.',
      painsTitle: 'Poznáte to?',
      pains: [
        ['🧾', 'Papierové kartičky sa strácajú', 'Hostia ich nechávajú doma a pečiatky sa dajú ľahko sfalšovať. Neviete, kto je váš stály zákazník.'],
        ['🕒', 'Prázdne doobedie a popoludnie', 'Na špičke rad, po obede prázdno. Nemáte ako prilákať hostí v tichých hodinách.'],
        ['👋', 'Noví hostia sa nevracajú', 'Človek príde raz — a zmizne. Kontaktovať ho už nemôžete.'],
      ],
      howTitle: 'Ako Loya pomáha kaviarňam',
      how: [
        ['☕', 'Pečiatková karta „10. káva zadarmo“', 'Nastavíte za minútu: koľko pečiatok a aký darček. Darček systém vyznačí sám.'],
        ['📱', 'Telefón baristu ako skener', 'Otvorte QR na obrazovke pokladne — telefón sa zmení na bezdrôtový skener. Pečiatka za 2 sekundy, rad nerastie.'],
        ['⏰', 'Dvojité pečiatky v tichých hodinách', 'Zapnite akciu na 14:00–17:00 — a hostia začnú chodiť v čase, keď je prázdno.'],
        ['💌', 'Automatické e-maily', 'Hosťovi, ktorému chýba krok do darčeka, ktorý mesiac neprišiel alebo má narodeniny, odíde e-mail sám.'],
      ],
      exampleTitle: 'Príklad',
      example: 'Kaviareň so 600 hosťami mesačne. Ak s vernostnou kartou príde aspoň 10 % z nich ešte raz pri priemernom účte 4 €, je to približne 240 € tržieb navyše mesačne — 24-krát viac než cena predplatného.',
      faq: [
        ['Potrebuje hosť samostatnú aplikáciu?', 'Nie. Karta sa otvorí cez odkaz alebo QR a uloží sa do Google Wallet alebo Telegramu. Dá sa aj vytlačiť plastová karta s QR.'],
        ['Potrebujem špeciálny skener?', 'Nie — stačí telefón ktoréhokoľvek zamestnanca. Funguje aj USB skener čiarových kódov, ak ho máte.'],
        ['Hodí sa pre pekáreň alebo malú sieť?', 'Áno. Pre viac prevádzok je tarif Pro: spoločná databáza, analytika pre každú prevádzku, zamestnanci a roly.'],
      ],
    },
    en: {
      name: 'For cafés & coffee shops',
      metaTitle: 'Loyalty program for cafés and coffee shops — Loya',
      metaDesc: 'A digital stamp card (“every 10th coffee free”), a scanner on the barista’s phone, automated emails and analytics for cafés, coffee shops and bakeries. 14 days free.',
      h1: 'Loyalty program', h1gold: 'for cafés & coffee shops',
      lead: 'A digital stamp card instead of a paper one: the guest shows a QR code, the barista scans it with a phone — and a week later the guest is back for the next cup.',
      painsTitle: 'Sound familiar?',
      pains: [
        ['🧾', 'Paper cards get lost', 'Guests leave them at home and stamps are easy to fake. You don’t know who your regulars are.'],
        ['🕒', 'Empty mid-morning and afternoon hours', 'There’s a queue at peak time and nobody after lunch — and no way to bring guests in during quiet hours.'],
        ['👋', 'New guests don’t come back', 'Someone visits once and disappears. You have no way to reach them.'],
      ],
      howTitle: 'How Loya helps cafés',
      how: [
        ['☕', '“10th coffee free” stamp card', 'Set it up in a minute: how many stamps and what reward. The reward is tracked automatically.'],
        ['📱', 'The barista’s phone is the scanner', 'Open the QR on the till screen and any phone becomes a wireless scanner. A stamp takes 2 seconds — the queue doesn’t grow.'],
        ['⏰', 'Double stamps in quiet hours', 'Turn on a 2–5 pm promo and guests start coming when it’s empty.'],
        ['💌', 'Automated emails', 'Guests one step from a reward, missing for a month or celebrating a birthday get an email automatically.'],
      ],
      exampleTitle: 'Example',
      example: 'A coffee shop with 600 guests a month. If the loyalty card brings just 10% of them back one extra time at an average €4 purchase, that’s about €240 of extra revenue a month — 24 times the subscription price.',
      faq: [
        ['Do guests need to install an app?', 'No. The card opens from a link or QR code and is saved to Google Wallet or Telegram. You can also print plastic cards with a QR code.'],
        ['Do I need a special scanner?', 'No — any staff member’s phone works. A USB barcode scanner works too if you have one.'],
        ['Does it work for a bakery or a small chain?', 'Yes. For several locations there’s the Pro plan: a shared database, per-location analytics, staff and roles.'],
      ],
    },
  },

  beauty: {
    slug: 'beauty-salon',
    icon: '💅',
    ru: {
      name: 'Для салонов красоты и барбершопов',
      metaTitle: 'Программа лояльности для салона красоты и барбершопа — Loya',
      metaDesc: 'Карты лояльности, напоминания о повторном визите, «Приведи подругу», поздравления с днём рождения и аналитика для салонов красоты, барбершопов, СПА и маникюра. 14 дней бесплатно.',
      h1: 'Программа лояльности', h1gold: 'для салонов красоты и барбершопов',
      lead: 'Клиент возвращается к своему мастеру не по памяти, а потому что вовремя получил напоминание и знает, что его ждёт бонус.',
      painsTitle: 'Знакомо?',
      pains: [
        ['📅', 'Клиенты пропадают между визитами', 'Человек стригся у вас два месяца назад и, возможно, уже ходит к другому мастеру.'],
        ['📒', 'База клиентов в блокноте или мессенджере', 'Нет истории визитов, не видно, кто ваш лучший клиент и кто давно не приходил.'],
        ['📣', 'Сарафанное радио работает само по себе', 'Клиенты рекомендуют вас друзьям, но это никак не поощряется и не считается.'],
      ],
      howTitle: 'Как Loya помогает салонам',
      how: [
        ['💳', 'Скидочная или накопительная карта', 'Процент скидки или бонус после нужной суммы — выберите то, что подходит вашим услугам.'],
        ['🔁', 'Возврат пропавших клиентов', 'Тем, кто давно не был, письмо уходит само — с поводом записаться снова.'],
        ['🎁', '«Приведи подругу» и день рождения', 'Бонус за рекомендацию и поздравление в день рождения — автоматически, без ручных напоминаний.'],
        ['👩‍🎨', 'Мастера и права доступа', 'У каждого мастера свой PIN. Видно, кто сколько клиентов обслужил.'],
      ],
      exampleTitle: 'Пример',
      example: 'Салон на 300 клиентов в месяц со средним чеком €30. Если 10% клиентов придут на один визит больше, это около €900 дополнительной выручки в месяц.',
      faq: [
        ['Подойдёт ли для барбершопа или ногтевой студии?', 'Да. Loya работает для любых услуг: стрижки, маникюр, косметология, массаж, СПА.'],
        ['Как клиенты получают карту?', 'По ссылке или QR на ресепшене: клиент вводит имя и телефон, а карта сохраняется в Google Wallet или Telegram.'],
        ['Можно ли просить отзывы?', 'Да, после визита можно автоматически отправлять просьбу оставить отзыв.'],
      ],
    },
    uk: {
      name: 'Для салонів краси та барбершопів',
      metaTitle: 'Програма лояльності для салону краси та барбершопу — Loya',
      metaDesc: 'Картки лояльності, нагадування про повторний візит, «Приведи подругу», привітання з днем народження й аналітика для салонів краси, барбершопів, СПА й манікюру. 14 днів безкоштовно.',
      h1: 'Програма лояльності', h1gold: 'для салонів краси та барбершопів',
      lead: 'Клієнт повертається до свого майстра не з пам’яті, а тому що вчасно отримав нагадування й знає, що на нього чекає бонус.',
      painsTitle: 'Знайомо?',
      pains: [
        ['📅', 'Клієнти зникають між візитами', 'Людина стриглася у вас два місяці тому і, можливо, вже ходить до іншого майстра.'],
        ['📒', 'База клієнтів у блокноті чи месенджері', 'Немає історії візитів, не видно, хто ваш найкращий клієнт і хто давно не приходив.'],
        ['📣', 'Сарафанне радіо працює саме по собі', 'Клієнти радять вас друзям, але це ніяк не заохочується й не рахується.'],
      ],
      howTitle: 'Як Loya допомагає салонам',
      how: [
        ['💳', 'Знижкова або накопичувальна картка', 'Відсоток знижки або бонус після потрібної суми — оберіть те, що пасує вашим послугам.'],
        ['🔁', 'Повернення зниклих клієнтів', 'Тим, хто давно не був, лист іде сам — із приводом записатися знову.'],
        ['🎁', '«Приведи подругу» й день народження', 'Бонус за рекомендацію й привітання в день народження — автоматично, без ручних нагадувань.'],
        ['👩‍🎨', 'Майстри та права доступу', 'У кожного майстра свій PIN. Видно, хто скільки клієнтів обслужив.'],
      ],
      exampleTitle: 'Приклад',
      example: 'Салон на 300 клієнтів на місяць із середнім чеком €30. Якщо 10% клієнтів прийдуть на один візит більше, це близько €900 додаткової виручки на місяць.',
      faq: [
        ['Чи підійде для барбершопу або нігтьової студії?', 'Так. Loya працює для будь-яких послуг: стрижки, манікюр, косметологія, масаж, СПА.'],
        ['Як клієнти отримують картку?', 'За посиланням або QR на рецепції: клієнт вводить ім’я й телефон, а картка зберігається в Google Wallet чи Telegram.'],
        ['Чи можна просити відгуки?', 'Так, після візиту можна автоматично надсилати прохання залишити відгук.'],
      ],
    },
    sk: {
      name: 'Pre kozmetické salóny a barbershopy',
      metaTitle: 'Vernostný program pre kozmetický salón a barbershop — Loya',
      metaDesc: 'Vernostné karty, pripomienky ďalšej návštevy, „Priveď kamarátku“, blahoželania k narodeninám a analytika pre kozmetické salóny, barbershopy, SPA a nechtové štúdiá. 14 dní zadarmo.',
      h1: 'Vernostný program', h1gold: 'pre salóny krásy a barbershopy',
      lead: 'Zákazník sa k svojmu majstrovi vracia nie náhodou, ale preto, že včas dostal pripomienku a vie, že ho čaká bonus.',
      painsTitle: 'Poznáte to?',
      pains: [
        ['📅', 'Zákazníci sa medzi návštevami strácajú', 'Človek bol u vás pred dvoma mesiacmi a možno už chodí k inému majstrovi.'],
        ['📒', 'Zákazníci v zošite alebo v messengeri', 'Žiadna história návštev — nevidíte, kto je váš najlepší zákazník a kto dlho neprišiel.'],
        ['📣', 'Odporúčania fungujú samy od seba', 'Zákazníci vás odporúčajú priateľom, no nič ich k tomu nemotivuje a nikto to nepočíta.'],
      ],
      howTitle: 'Ako Loya pomáha salónom',
      how: [
        ['💳', 'Zľavová alebo bodová karta', 'Percento zľavy alebo bonus po dosiahnutí sumy — vyberte, čo sa hodí k vašim službám.'],
        ['🔁', 'Návrat stratených zákazníkov', 'Tým, ktorí dlho neprišli, odíde e-mail sám — s dôvodom znova sa objednať.'],
        ['🎁', '„Priveď kamarátku“ a narodeniny', 'Bonus za odporúčanie a blahoželanie k narodeninám — automaticky, bez ručného pripomínania.'],
        ['👩‍🎨', 'Majstri a prístupové práva', 'Každý majster má vlastný PIN. Vidíte, kto koľko zákazníkov obslúžil.'],
      ],
      exampleTitle: 'Príklad',
      example: 'Salón s 300 zákazníkmi mesačne a priemerným účtom 30 €. Ak 10 % zákazníkov príde o jednu návštevu viac, je to približne 900 € tržieb navyše mesačne.',
      faq: [
        ['Hodí sa pre barbershop alebo nechtové štúdio?', 'Áno. Loya funguje pre akékoľvek služby: strihanie, manikúru, kozmetiku, masáže, SPA.'],
        ['Ako zákazníci dostanú kartu?', 'Cez odkaz alebo QR na recepcii: zákazník zadá meno a telefón a karta sa uloží do Google Wallet alebo Telegramu.'],
        ['Môžem žiadať o recenzie?', 'Áno, po návšteve môžete automaticky posielať prosbu o recenziu.'],
      ],
    },
    en: {
      name: 'For beauty salons & barbershops',
      metaTitle: 'Loyalty program for beauty salons and barbershops — Loya',
      metaDesc: 'Loyalty cards, repeat-visit reminders, “Bring a friend”, birthday greetings and analytics for beauty salons, barbershops, spas and nail studios. 14 days free.',
      h1: 'Loyalty program', h1gold: 'for beauty salons & barbershops',
      lead: 'Clients return to their stylist not by chance, but because they got a reminder at the right time and know a bonus is waiting.',
      painsTitle: 'Sound familiar?',
      pains: [
        ['📅', 'Clients drift away between visits', 'Someone had a haircut with you two months ago and may already be seeing another stylist.'],
        ['📒', 'Clients in a notebook or a messenger', 'No visit history — you can’t see who your best clients are or who hasn’t been back.'],
        ['📣', 'Word of mouth goes unrewarded', 'Clients recommend you to friends, but nothing rewards it and nobody keeps track.'],
      ],
      howTitle: 'How Loya helps salons',
      how: [
        ['💳', 'Discount or points card', 'A percentage discount or a bonus after a set amount — pick what fits your services.'],
        ['🔁', 'Win back lost clients', 'Clients who haven’t visited in a while get an email automatically, with a reason to book again.'],
        ['🎁', '“Bring a friend” and birthdays', 'A referral bonus and a birthday greeting — automatic, no manual reminders.'],
        ['👩‍🎨', 'Stylists and access rights', 'Every stylist has their own PIN. You see who served how many clients.'],
      ],
      exampleTitle: 'Example',
      example: 'A salon with 300 clients a month and an average ticket of €30. If 10% of clients come back for one extra visit, that’s about €900 of extra revenue a month.',
      faq: [
        ['Does it work for a barbershop or nail studio?', 'Yes. Loya works for any service: haircuts, nails, cosmetics, massage, spa.'],
        ['How do clients get a card?', 'From a link or a QR code at the front desk: the client enters a name and phone number, and the card is saved to Google Wallet or Telegram.'],
        ['Can I ask for reviews?', 'Yes — after a visit, a review request can be sent automatically.'],
      ],
    },
  },

  shop: {
    slug: 'shop',
    icon: '🛍️',
    ru: {
      name: 'Для магазинов',
      metaTitle: 'Программа лояльности для магазина — Loya',
      metaDesc: 'Накопительные и скидочные карты, бонусы после нужной суммы, товары и склад, рассылки и аналитика покупок для небольших магазинов одежды, косметики, цветов и подарков. 14 дней бесплатно.',
      h1: 'Программа лояльности', h1gold: 'для магазина',
      lead: 'Покупатель видит свои бонусы в телефоне, получает письмо о новинках и приходит снова — к вам, а не к соседнему магазину или маркетплейсу.',
      painsTitle: 'Знакомо?',
      pains: [
        ['🛒', 'Покупатели уходят на маркетплейсы', 'Цена везде похожая — и у человека нет причины возвращаться именно к вам.'],
        ['🤷', 'Вы не знаете своих покупателей', 'Кто покупает чаще, на какую сумму и когда приходил в последний раз — непонятно.'],
        ['📦', 'Акции и новинки никто не видит', 'Объявление в соцсетях увидели не те, кто реально у вас покупает.'],
      ],
      howTitle: 'Как Loya помогает магазинам',
      how: [
        ['💰', 'Накопительная карта с бонусом', 'Бонус или подарок после нужной суммы покупок — покупатель видит, сколько осталось.'],
        ['🧾', 'Товары, склад и чеки', 'В тарифе Starter — товары, остатки и чеки из кассы, привязанные к карте покупателя.'],
        ['💌', 'Рассылки своим покупателям', 'Email и Telegram с готовыми текстами: новинки, распродажа, «давно не заходили».'],
        ['📊', 'Аналитика покупок', 'Выручка, средний чек, воронка лояльности и тепловая карта — когда приходят и когда запускать акции.'],
      ],
      exampleTitle: 'Пример',
      example: 'Магазин на 400 покупателей в месяц со средним чеком €25. Если 10% из них сделают одну покупку больше, это около €1000 дополнительной выручки в месяц.',
      faq: [
        ['Подойдёт ли для магазина одежды, косметики или цветов?', 'Да. Loya подходит для любой розницы, где покупатели возвращаются: одежда, косметика, цветы, подарки, зоотовары.'],
        ['Работает ли с кассой?', 'Можно подключить чеки из кассы через POS-ключ, а можно отмечать покупки вручную или сканером.'],
        ['Если у меня несколько магазинов?', 'Для нескольких точек есть тариф Pro: общая база, аналитика по каждой точке и общий обмен данными между компьютерами.'],
      ],
    },
    uk: {
      name: 'Для магазинів',
      metaTitle: 'Програма лояльності для магазину — Loya',
      metaDesc: 'Накопичувальні та знижкові картки, бонуси після потрібної суми, товари й склад, розсилки й аналітика покупок для невеликих магазинів одягу, косметики, квітів і подарунків. 14 днів безкоштовно.',
      h1: 'Програма лояльності', h1gold: 'для магазину',
      lead: 'Покупець бачить свої бонуси в телефоні, отримує лист про новинки й приходить знову — до вас, а не до сусіднього магазину чи маркетплейсу.',
      painsTitle: 'Знайомо?',
      pains: [
        ['🛒', 'Покупці йдуть на маркетплейси', 'Ціна скрізь схожа — і в людини немає причини повертатися саме до вас.'],
        ['🤷', 'Ви не знаєте своїх покупців', 'Хто купує частіше, на яку суму й коли приходив востаннє — незрозуміло.'],
        ['📦', 'Акції й новинки ніхто не бачить', 'Оголошення в соцмережах побачили не ті, хто справді у вас купує.'],
      ],
      howTitle: 'Як Loya допомагає магазинам',
      how: [
        ['💰', 'Накопичувальна картка з бонусом', 'Бонус або подарунок після потрібної суми покупок — покупець бачить, скільки лишилося.'],
        ['🧾', 'Товари, склад і чеки', 'У тарифі Starter — товари, залишки й чеки з каси, прив’язані до картки покупця.'],
        ['💌', 'Розсилки своїм покупцям', 'Email і Telegram із готовими текстами: новинки, розпродаж, «давно не заходили».'],
        ['📊', 'Аналітика покупок', 'Виручка, середній чек, воронка лояльності й теплова карта — коли приходять і коли запускати акції.'],
      ],
      exampleTitle: 'Приклад',
      example: 'Магазин на 400 покупців на місяць із середнім чеком €25. Якщо 10% із них зроблять одну покупку більше, це близько €1000 додаткової виручки на місяць.',
      faq: [
        ['Чи підійде для магазину одягу, косметики чи квітів?', 'Так. Loya пасує будь-якій роздрібній торгівлі, куди покупці повертаються: одяг, косметика, квіти, подарунки, зоотовари.'],
        ['Чи працює з касою?', 'Можна підключити чеки з каси через POS-ключ, а можна позначати покупки вручну чи сканером.'],
        ['Якщо в мене кілька магазинів?', 'Для кількох точок є тариф Pro: спільна база, аналітика по кожній точці й спільний обмін даними між комп’ютерами.'],
      ],
    },
    sk: {
      name: 'Pre obchody',
      metaTitle: 'Vernostný program pre obchod — Loya',
      metaDesc: 'Bodové a zľavové karty, bonusy po dosiahnutí sumy, tovar a sklad, kampane a analytika nákupov pre malé obchody s oblečením, kozmetikou, kvetmi a darčekmi. 14 dní zadarmo.',
      h1: 'Vernostný program', h1gold: 'pre obchody',
      lead: 'Zákazník vidí svoje bonusy v telefóne, dostane e-mail o novinkách a príde znova — k vám, nie do susedného obchodu ani na marketplace.',
      painsTitle: 'Poznáte to?',
      pains: [
        ['🛒', 'Zákazníci odchádzajú na marketplace', 'Cena je všade podobná — a človek nemá dôvod vracať sa práve k vám.'],
        ['🤷', 'Svojich zákazníkov nepoznáte', 'Kto nakupuje častejšie, za koľko a kedy bol naposledy — netušíte.'],
        ['📦', 'Akcie a novinky nikto nevidí', 'Príspevok na sociálnych sieťach videli iní ľudia než tí, ktorí u vás naozaj nakupujú.'],
      ],
      howTitle: 'Ako Loya pomáha obchodom',
      how: [
        ['💰', 'Bodová karta s bonusom', 'Bonus alebo darček po dosiahnutí sumy nákupov — zákazník vidí, koľko mu zostáva.'],
        ['🧾', 'Tovar, sklad a účtenky', 'V tarife Starter — tovar, zásoby a účtenky z pokladne priradené ku karte zákazníka.'],
        ['💌', 'Kampane pre vlastných zákazníkov', 'E-mail a Telegram s hotovými textami: novinky, výpredaj, „dlho ste u nás neboli“.'],
        ['📊', 'Analytika nákupov', 'Tržby, priemerný nákup, vernostný lievik a teplotná mapa — kedy zákazníci chodia a kedy spustiť akciu.'],
      ],
      exampleTitle: 'Príklad',
      example: 'Obchod so 400 zákazníkmi mesačne a priemerným nákupom 25 €. Ak 10 % z nich nakúpi ešte raz, je to približne 1000 € tržieb navyše mesačne.',
      faq: [
        ['Hodí sa pre obchod s oblečením, kozmetikou alebo kvetmi?', 'Áno. Loya sa hodí pre akýkoľvek maloobchod, kam sa zákazníci vracajú: oblečenie, kozmetika, kvety, darčeky, chovateľské potreby.'],
        ['Funguje s pokladňou?', 'Účtenky z pokladne môžete pripojiť cez POS kľúč, alebo nákupy zaznamenávať ručne či skenerom.'],
        ['Čo ak mám viac obchodov?', 'Pre viac prevádzok je tarif Pro: spoločná databáza, analytika pre každú prevádzku a spoločná výmena údajov medzi počítačmi.'],
      ],
    },
    en: {
      name: 'For shops',
      metaTitle: 'Loyalty program for retail shops — Loya',
      metaDesc: 'Points and discount cards, rewards after a set amount, products and stock, campaigns and purchase analytics for small clothing, cosmetics, flower and gift shops. 14 days free.',
      h1: 'Loyalty program', h1gold: 'for retail shops',
      lead: 'Customers see their rewards on their phone, get an email about new arrivals and come back — to you, not to the shop next door or a marketplace.',
      painsTitle: 'Sound familiar?',
      pains: [
        ['🛒', 'Customers drift to marketplaces', 'Prices are similar everywhere — so there’s no reason to come back to you in particular.'],
        ['🤷', 'You don’t know your customers', 'Who buys most often, how much, and when they last visited — it’s all a guess.'],
        ['📦', 'Nobody sees your promos and new arrivals', 'Your social media post reached people other than the ones who actually buy from you.'],
      ],
      howTitle: 'How Loya helps shops',
      how: [
        ['💰', 'Points card with a reward', 'A bonus or gift after a set amount spent — customers see how much is left.'],
        ['🧾', 'Products, stock and receipts', 'The Starter plan includes products, stock levels and till receipts linked to the customer’s card.'],
        ['💌', 'Campaigns to your own customers', 'Email and Telegram with ready-made texts: new arrivals, sales, “we haven’t seen you in a while”.'],
        ['📊', 'Purchase analytics', 'Revenue, average purchase, loyalty funnel and a heatmap — when customers come and when to run promotions.'],
      ],
      exampleTitle: 'Example',
      example: 'A shop with 400 customers a month and an average purchase of €25. If 10% of them make one extra purchase, that’s about €1,000 of extra revenue a month.',
      faq: [
        ['Does it work for clothing, cosmetics or flower shops?', 'Yes. Loya fits any retail business where customers come back: clothing, cosmetics, flowers, gifts, pet supplies.'],
        ['Does it work with my till?', 'You can connect till receipts with a POS key, or record purchases manually or with a scanner.'],
        ['What if I have several shops?', 'For several locations there’s the Pro plan: a shared database, per-location analytics and data sync between computers.'],
      ],
    },
  },

  travel: {
    slug: 'travel-agency',
    icon: '✈️',
    ru: {
      name: 'Для туристических агентств',
      metaTitle: 'Программа лояльности для турагентства и туристической фирмы — Loya',
      metaDesc: 'Накопительные карты, бонусы за повторные поездки и рекомендации, рассылки к сезону и поздравления для турагентств и туристических фирм. 14 дней бесплатно.',
      h1: 'Программа лояльности', h1gold: 'для турагентств',
      lead: 'Клиент, который съездил с вами один раз, должен вернуться за следующей поездкой — и привести друзей. Loya напомнит о вас вовремя и наградит за верность.',
      painsTitle: 'Знакомо?',
      pains: [
        ['📅', 'Клиенты покупают раз в год', 'Между поездками проходят месяцы — и к следующему отпуску человек уже не помнит, у кого покупал тур.'],
        ['🛒', 'Цены сравнивают с онлайн-сервисами', 'Тур можно найти дешевле в интернете, и без причины остаться клиент уходит.'],
        ['📣', 'Рекомендации никак не поощряются', 'Довольные клиенты советуют вас знакомым, но это не учитывается и не вознаграждается.'],
      ],
      howTitle: 'Как Loya помогает турагентствам',
      how: [
        ['💰', 'Бонусы за каждую поездку', 'Накопительная карта: процент от суммы тура возвращается бонусами на следующую поездку.'],
        ['🎁', '«Приведи друга»', 'Бонус клиенту за каждого нового туриста по рекомендации — автоматически.'],
        ['💌', 'Рассылки к сезону', 'Email и Telegram перед летом, зимними праздниками и горящими предложениями — с готовыми текстами.'],
        ['🔁', 'Возврат «уснувших» клиентов', 'Тем, кто давно не путешествовал с вами, Loya сама отправит повод вернуться.'],
      ],
      exampleTitle: 'Пример',
      example: 'Агентство продаёт 80 туров в месяц со средним чеком €900. Если благодаря бонусам и напоминаниям всего 5% клиентов купят ещё один тур, это около €3600 дополнительной выручки в месяц.',
      faq: [
        ['Подойдёт ли, если клиенты приходят редко?', 'Да, именно для этого: накопительная карта и рассылки удерживают клиента между поездками, а бонус ждёт его к следующему отпуску.'],
        ['Нужно ли клиенту приходить в офис?', 'Нет. Карта открывается по ссылке или QR и хранится в Google Wallet или Telegram, отметку можно поставить по коду карты.'],
        ['Можно ли работать с несколькими офисами?', 'Да, для нескольких точек есть тариф Pro: общая база, сотрудники и аналитика по каждому офису.'],
      ],
    },
    uk: {
      name: 'Для туристичних агенцій',
      metaTitle: 'Програма лояльності для турагенції та туристичної фірми — Loya',
      metaDesc: 'Накопичувальні картки, бонуси за повторні поїздки й рекомендації, розсилки до сезону та привітання для турагенцій і туристичних фірм. 14 днів безкоштовно.',
      h1: 'Програма лояльності', h1gold: 'для турагенцій',
      lead: 'Клієнт, який з’їздив з вами один раз, має повернутися по наступну поїздку — і привести друзів. Loya вчасно нагадає про вас і винагородить за вірність.',
      painsTitle: 'Знайомо?',
      pains: [
        ['📅', 'Клієнти купують раз на рік', 'Між поїздками минають місяці — і до наступної відпустки людина вже не пам’ятає, у кого купувала тур.'],
        ['🛒', 'Ціни порівнюють з онлайн-сервісами', 'Тур можна знайти дешевше в інтернеті, і без причини лишитися клієнт іде.'],
        ['📣', 'Рекомендації ніяк не заохочуються', 'Задоволені клієнти радять вас знайомим, але це не враховується й не винагороджується.'],
      ],
      howTitle: 'Як Loya допомагає турагенціям',
      how: [
        ['💰', 'Бонуси за кожну поїздку', 'Накопичувальна картка: відсоток від суми туру повертається бонусами на наступну поїздку.'],
        ['🎁', '«Приведи друга»', 'Бонус клієнту за кожного нового туриста за рекомендацією — автоматично.'],
        ['💌', 'Розсилки до сезону', 'Email і Telegram перед літом, зимовими святами й гарячими пропозиціями — з готовими текстами.'],
        ['🔁', 'Повернення «заснулих» клієнтів', 'Тим, хто давно не подорожував з вами, Loya сама надішле привід повернутися.'],
      ],
      exampleTitle: 'Приклад',
      example: 'Агенція продає 80 турів на місяць із середнім чеком €900. Якщо завдяки бонусам і нагадуванням лише 5% клієнтів куплять ще один тур, це близько €3600 додаткової виручки на місяць.',
      faq: [
        ['Чи підійде, якщо клієнти приходять рідко?', 'Так, саме для цього: накопичувальна картка й розсилки утримують клієнта між поїздками, а бонус чекає на нього до наступної відпустки.'],
        ['Чи потрібно клієнту приходити в офіс?', 'Ні. Картка відкривається за посиланням або QR і зберігається в Google Wallet чи Telegram, позначку можна поставити за кодом картки.'],
        ['Чи можна працювати з кількома офісами?', 'Так, для кількох точок є тариф Pro: спільна база, працівники й аналітика по кожному офісу.'],
      ],
    },
    sk: {
      name: 'Pre cestovné kancelárie',
      metaTitle: 'Vernostný program pre cestovnú kanceláriu a agentúru — Loya',
      metaDesc: 'Bodové karty, bonusy za ďalšie zájazdy a odporúčania, kampane pred sezónou a blahoželania pre cestovné kancelárie a agentúry. 14 dní zadarmo.',
      h1: 'Vernostný program', h1gold: 'pre cestovné kancelárie',
      lead: 'Klient, ktorý s vami raz cestoval, sa má vrátiť na ďalší zájazd — a priviesť priateľov. Loya vás včas pripomenie a odmení ho za vernosť.',
      painsTitle: 'Poznáte to?',
      pains: [
        ['📅', 'Klienti nakupujú raz do roka', 'Medzi cestami ubehnú mesiace — a pred ďalšou dovolenkou si človek nepamätá, kde zájazd kúpil.'],
        ['🛒', 'Ceny porovnávajú s online službami', 'Zájazd sa dá nájsť lacnejšie na internete a bez dôvodu zostať klient odíde.'],
        ['📣', 'Odporúčania nik neodmeňuje', 'Spokojní klienti vás odporúčajú známym, no nikto to nesleduje ani neodmeňuje.'],
      ],
      howTitle: 'Ako Loya pomáha cestovným kanceláriám',
      how: [
        ['💰', 'Bonusy za každý zájazd', 'Bodová karta: percento zo sumy zájazdu sa vráti ako bonus na ďalšiu cestu.'],
        ['🎁', '„Priveď kamaráta“', 'Bonus klientovi za každého nového cestovateľa na odporúčanie — automaticky.'],
        ['💌', 'Kampane pred sezónou', 'E-mail a Telegram pred letom, zimnými sviatkami a last minute ponukami — s hotovými textami.'],
        ['🔁', 'Návrat „spiacich“ klientov', 'Tým, ktorí s vami dlho necestovali, Loya sama pošle dôvod vrátiť sa.'],
      ],
      exampleTitle: 'Príklad',
      example: 'Kancelária predá 80 zájazdov mesačne pri priemernej cene 900 €. Ak vďaka bonusom a pripomienkam kúpi ďalší zájazd len 5 % klientov, je to približne 3600 € tržieb navyše mesačne.',
      faq: [
        ['Hodí sa, ak klienti chodia zriedka?', 'Áno, práve na to: bodová karta a kampane udržia klienta medzi cestami a bonus naňho čaká pri ďalšej dovolenke.'],
        ['Musí klient prísť do kancelárie?', 'Nie. Karta sa otvorí cez odkaz alebo QR a uloží sa do Google Wallet alebo Telegramu, nákup sa dá zaznamenať podľa kódu karty.'],
        ['Dá sa pracovať s viacerými pobočkami?', 'Áno, pre viac prevádzok je tarif Pro: spoločná databáza, zamestnanci a analytika pre každú pobočku.'],
      ],
    },
    en: {
      name: 'For travel agencies',
      metaTitle: 'Loyalty program for travel agencies and tour operators — Loya',
      metaDesc: 'Points cards, rewards for repeat trips and referrals, seasonal campaigns and greetings for travel agencies and tour operators. 14 days free.',
      h1: 'Loyalty program', h1gold: 'for travel agencies',
      lead: 'A client who travelled with you once should come back for the next trip — and bring friends. Loya reminds them of you at the right time and rewards their loyalty.',
      painsTitle: 'Sound familiar?',
      pains: [
        ['📅', 'Clients buy once a year', 'Months pass between trips — and by the next holiday they no longer remember where they booked.'],
        ['🛒', 'Prices get compared with online services', 'A tour can be found cheaper online, and without a reason to stay, the client leaves.'],
        ['📣', 'Referrals go unrewarded', 'Happy clients recommend you to friends, but nobody tracks or rewards it.'],
      ],
      howTitle: 'How Loya helps travel agencies',
      how: [
        ['💰', 'Rewards for every trip', 'A points card: a percentage of each booking comes back as a bonus towards the next trip.'],
        ['🎁', '“Bring a friend”', 'A bonus for every new traveller a client refers — automatically.'],
        ['💌', 'Seasonal campaigns', 'Email and Telegram before summer, winter holidays and last-minute deals — with ready-made texts.'],
        ['🔁', 'Win back “sleeping” clients', 'Clients who haven’t travelled with you in a while get a reason to come back, sent by Loya.'],
      ],
      exampleTitle: 'Example',
      example: 'An agency sells 80 trips a month with an average booking of €900. If rewards and reminders bring just 5% of clients back for one more trip, that’s about €3,600 of extra revenue a month.',
      faq: [
        ['Does it work if clients come rarely?', 'Yes — that’s exactly what it’s for: the points card and campaigns keep clients between trips, and their bonus waits for the next holiday.'],
        ['Do clients have to visit the office?', 'No. The card opens from a link or QR code and is saved to Google Wallet or Telegram; a purchase can be recorded by the card code.'],
        ['Can I run several offices?', 'Yes — the Pro plan covers several locations: a shared database, staff and per-office analytics.'],
      ],
    },
  },

  photo: {
    slug: 'photo-studio',
    icon: '📷',
    ru: {
      name: 'Для фотостудий',
      metaTitle: 'Программа лояльности для фотостудии и фотографа — Loya',
      metaDesc: 'Карты визитов, бонусы за повторные съёмки и рекомендации, напоминания и рассылки для фотостудий, фотографов и студий аренды. 14 дней бесплатно.',
      h1: 'Программа лояльности', h1gold: 'для фотостудий',
      lead: 'Семейная съёмка раз в год, портфолио, выпускной, свадьба — у каждого клиента есть повод вернуться. Loya напомнит о нём и сделает так, чтобы вернулись именно к вам.',
      painsTitle: 'Знакомо?',
      pains: [
        ['📅', 'Съёмка — событие редкое', 'Клиент приходит раз в полгода или год, и за это время легко находит другую студию.'],
        ['📒', 'Контакты разбросаны по мессенджерам', 'Нет общей базы: кто снимался, когда и что заказывал — не видно.'],
        ['📣', 'Сарафанное радио без награды', 'Клиенты делятся фото и советуют вас, но никак не получают за это бонус.'],
      ],
      howTitle: 'Как Loya помогает фотостудиям',
      how: [
        ['💳', 'Карта съёмок со скидкой', 'Каждая 5-я съёмка со скидкой или бонус после нужной суммы — выбирайте, что подходит.'],
        ['🔁', 'Напоминание о следующей съёмке', 'Тем, кто давно не приходил, письмо уходит само: «Пора обновить семейные фото?»'],
        ['🎁', '«Приведи подругу» и отзывы', 'Бонус за рекомендацию и автоматическая просьба оставить отзыв после съёмки.'],
        ['👩‍🎨', 'Фотографы и залы', 'У каждого фотографа свой PIN, видно, кто сколько клиентов привёл и обслужил.'],
      ],
      exampleTitle: 'Пример',
      example: 'Студия проводит 120 съёмок в месяц со средним чеком €80. Если 10% клиентов вернутся ещё на одну съёмку, это около €960 дополнительной выручки в месяц.',
      faq: [
        ['Подойдёт ли для фотографа без своей студии?', 'Да. Loya работает на ноутбуке, а карты клиентов хранятся у них в телефоне — студия не обязательна.'],
        ['Можно ли использовать для аренды зала?', 'Да, отмечайте каждую аренду визитом или суммой — постоянные арендаторы получат бонус.'],
        ['Клиентам нужно что-то устанавливать?', 'Нет. Карта открывается по ссылке или QR и сохраняется в Google Wallet или Telegram.'],
      ],
    },
    uk: {
      name: 'Для фотостудій',
      metaTitle: 'Програма лояльності для фотостудії та фотографа — Loya',
      metaDesc: 'Картки візитів, бонуси за повторні зйомки й рекомендації, нагадування та розсилки для фотостудій, фотографів і студій оренди. 14 днів безкоштовно.',
      h1: 'Програма лояльності', h1gold: 'для фотостудій',
      lead: 'Сімейна зйомка раз на рік, портфоліо, випускний, весілля — у кожного клієнта є привід повернутися. Loya нагадає про нього й зробить так, щоб повернулися саме до вас.',
      painsTitle: 'Знайомо?',
      pains: [
        ['📅', 'Зйомка — подія рідкісна', 'Клієнт приходить раз на пів року чи рік і за цей час легко знаходить іншу студію.'],
        ['📒', 'Контакти розкидані по месенджерах', 'Немає спільної бази: хто знімався, коли і що замовляв — не видно.'],
        ['📣', 'Сарафанне радіо без нагороди', 'Клієнти діляться фото й радять вас, але ніяк не отримують за це бонус.'],
      ],
      howTitle: 'Як Loya допомагає фотостудіям',
      how: [
        ['💳', 'Картка зйомок зі знижкою', 'Кожна 5-та зйомка зі знижкою або бонус після потрібної суми — обирайте, що пасує.'],
        ['🔁', 'Нагадування про наступну зйомку', 'Тим, хто давно не приходив, лист іде сам: «Час оновити сімейні фото?»'],
        ['🎁', '«Приведи подругу» й відгуки', 'Бонус за рекомендацію й автоматичне прохання залишити відгук після зйомки.'],
        ['👩‍🎨', 'Фотографи й зали', 'У кожного фотографа свій PIN, видно, хто скільки клієнтів привів і обслужив.'],
      ],
      exampleTitle: 'Приклад',
      example: 'Студія проводить 120 зйомок на місяць із середнім чеком €80. Якщо 10% клієнтів повернуться ще на одну зйомку, це близько €960 додаткової виручки на місяць.',
      faq: [
        ['Чи підійде фотографу без власної студії?', 'Так. Loya працює на ноутбуці, а картки клієнтів зберігаються в них у телефоні — студія не обов’язкова.'],
        ['Чи можна використовувати для оренди залу?', 'Так, позначайте кожну оренду візитом або сумою — постійні орендарі отримають бонус.'],
        ['Клієнтам потрібно щось встановлювати?', 'Ні. Картка відкривається за посиланням або QR і зберігається в Google Wallet чи Telegram.'],
      ],
    },
    sk: {
      name: 'Pre fotoštúdiá',
      metaTitle: 'Vernostný program pre fotoštúdio a fotografa — Loya',
      metaDesc: 'Karty návštev, bonusy za ďalšie fotenia a odporúčania, pripomienky a kampane pre fotoštúdiá, fotografov a prenájom ateliérov. 14 dní zadarmo.',
      h1: 'Vernostný program', h1gold: 'pre fotoštúdiá',
      lead: 'Rodinné fotenie raz do roka, portfólio, stužková, svadba — každý klient má dôvod vrátiť sa. Loya mu ho pripomenie a postará sa, aby sa vrátil práve k vám.',
      painsTitle: 'Poznáte to?',
      pains: [
        ['📅', 'Fotenie je zriedkavá udalosť', 'Klient príde raz za pol roka či rok a medzitým ľahko nájde iné štúdio.'],
        ['📒', 'Kontakty roztrúsené v messengeroch', 'Žiadna spoločná databáza: kto sa fotil, kedy a čo si objednal — nevidno.'],
        ['📣', 'Odporúčania bez odmeny', 'Klienti zdieľajú fotky a odporúčajú vás, no nič za to nedostanú.'],
      ],
      howTitle: 'Ako Loya pomáha fotoštúdiám',
      how: [
        ['💳', 'Karta fotení so zľavou', 'Každé 5. fotenie so zľavou alebo bonus po dosiahnutí sumy — vyberte, čo vám sedí.'],
        ['🔁', 'Pripomienka ďalšieho fotenia', 'Tým, ktorí dlho neprišli, odíde e-mail sám: „Nie je čas na nové rodinné fotky?“'],
        ['🎁', '„Priveď kamarátku“ a recenzie', 'Bonus za odporúčanie a automatická prosba o recenziu po fotení.'],
        ['👩‍🎨', 'Fotografi a ateliéry', 'Každý fotograf má vlastný PIN, vidíte, kto koľko klientov priviedol a obslúžil.'],
      ],
      exampleTitle: 'Príklad',
      example: 'Štúdio má 120 fotení mesačne pri priemernej cene 80 €. Ak sa 10 % klientov vráti na ďalšie fotenie, je to približne 960 € tržieb navyše mesačne.',
      faq: [
        ['Hodí sa pre fotografa bez vlastného štúdia?', 'Áno. Loya beží na notebooku a karty klientov majú v telefóne — štúdio nie je podmienkou.'],
        ['Dá sa použiť na prenájom ateliéru?', 'Áno, každý prenájom zaznamenajte ako návštevu alebo sumu — stáli nájomcovia dostanú bonus.'],
        ['Musia klienti niečo inštalovať?', 'Nie. Karta sa otvorí cez odkaz alebo QR a uloží sa do Google Wallet alebo Telegramu.'],
      ],
    },
    en: {
      name: 'For photo studios',
      metaTitle: 'Loyalty program for photo studios and photographers — Loya',
      metaDesc: 'Visit cards, rewards for repeat shoots and referrals, reminders and campaigns for photo studios, photographers and studio rentals. 14 days free.',
      h1: 'Loyalty program', h1gold: 'for photo studios',
      lead: 'A yearly family shoot, a portfolio, graduation, a wedding — every client has a reason to come back. Loya reminds them and makes sure they come back to you.',
      painsTitle: 'Sound familiar?',
      pains: [
        ['📅', 'A shoot is a rare event', 'Clients come once every six months or a year — plenty of time to find another studio.'],
        ['📒', 'Contacts scattered across messengers', 'No shared database: who had a shoot, when, and what they ordered is invisible.'],
        ['📣', 'Word of mouth goes unrewarded', 'Clients share their photos and recommend you, but get nothing for it.'],
      ],
      howTitle: 'How Loya helps photo studios',
      how: [
        ['💳', 'Shoot card with a discount', 'Every 5th shoot discounted or a bonus after a set amount — pick what fits.'],
        ['🔁', 'Reminder for the next shoot', 'Clients who haven’t been back in a while get an email automatically: “Time to refresh the family photos?”'],
        ['🎁', '“Bring a friend” and reviews', 'A referral bonus and an automatic review request after each shoot.'],
        ['👩‍🎨', 'Photographers and rooms', 'Every photographer has their own PIN; you see who brought in and served how many clients.'],
      ],
      exampleTitle: 'Example',
      example: 'A studio runs 120 shoots a month at an average €80. If 10% of clients come back for one more shoot, that’s about €960 of extra revenue a month.',
      faq: [
        ['Does it work for a photographer without a studio?', 'Yes. Loya runs on a laptop and the clients’ cards live on their phones — no studio required.'],
        ['Can I use it for studio rentals?', 'Yes — record each rental as a visit or an amount, and regular renters earn a bonus.'],
        ['Do clients need to install anything?', 'No. The card opens from a link or QR code and is saved to Google Wallet or Telegram.'],
      ],
    },
  },

  grooming: {
    slug: 'pet-grooming',
    icon: '🐾',
    ru: {
      name: 'Для груминг-салонов',
      metaTitle: 'Программа лояльности для груминг-салона и зоосалона — Loya',
      metaDesc: 'Штамп-карта «каждый 6-й груминг со скидкой», напоминания о следующей стрижке питомца, «Приведи друга» и аналитика для груминг-салонов и зоосалонов. 14 дней бесплатно.',
      h1: 'Программа лояльности', h1gold: 'для груминг-салонов',
      lead: 'Питомцу нужна стрижка каждые 6–8 недель. Loya заметит, когда клиент задерживается, напомнит о визите и наградит за верность вашему салону.',
      painsTitle: 'Знакомо?',
      pains: [
        ['🕒', 'Клиенты пропускают сроки', 'Пора на стрижку, а владелец забыл — и записался туда, где оказалось ближе.'],
        ['📒', 'Запись в блокноте', 'Не видно, когда питомец был в последний раз и кто из клиентов самый постоянный.'],
        ['👋', 'Новые клиенты приходят один раз', 'Попробовали, ушли — и связаться с ними больше нельзя.'],
      ],
      howTitle: 'Как Loya помогает груминг-салонам',
      how: [
        ['🐾', 'Штамп-карта для питомцев', '«Каждый 6-й груминг со скидкой 50%» — штамп ставится телефоном за пару секунд.'],
        ['🔁', 'Напоминание о стрижке', 'Если клиент не пришёл в привычный срок, письмо уходит само: «Пора освежить шерсть?»'],
        ['🎁', '«Приведи друга»', 'Бонус за каждого нового клиента с питомцем по рекомендации.'],
        ['📊', 'Аналитика салона', 'Сколько постоянных клиентов, кто давно не был, когда пиковые дни — всё на одном экране.'],
      ],
      exampleTitle: 'Пример',
      example: 'Салон обслуживает 200 питомцев в месяц со средним чеком €40. Если 10% клиентов будут приходить на один визит чаще, это около €800 дополнительной выручки в месяц.',
      faq: [
        ['Подойдёт ли для зоосалона с магазином?', 'Да. Можно вести и визиты на груминг, и покупки кормов — с накопительными бонусами.'],
        ['Как клиент получает карту?', 'По ссылке или QR на стойке: владелец вводит имя и телефон, карта сохраняется в Google Wallet или Telegram.'],
        ['Если у клиента несколько питомцев?', 'Ведите отдельную карту на каждого питомца или одну общую на владельца — как удобнее вам.'],
      ],
    },
    uk: {
      name: 'Для грумінг-салонів',
      metaTitle: 'Програма лояльності для грумінг-салону та зоосалону — Loya',
      metaDesc: 'Штамп-картка «кожен 6-й грумінг зі знижкою», нагадування про наступну стрижку улюбленця, «Приведи друга» й аналітика для грумінг-салонів і зоосалонів. 14 днів безкоштовно.',
      h1: 'Програма лояльності', h1gold: 'для грумінг-салонів',
      lead: 'Улюбленцю потрібна стрижка кожні 6–8 тижнів. Loya помітить, коли клієнт затримується, нагадає про візит і винагородить за вірність вашому салону.',
      painsTitle: 'Знайомо?',
      pains: [
        ['🕒', 'Клієнти пропускають терміни', 'Час на стрижку, а власник забув — і записався туди, де виявилося ближче.'],
        ['📒', 'Запис у блокноті', 'Не видно, коли улюбленець був востаннє і хто з клієнтів найпостійніший.'],
        ['👋', 'Нові клієнти приходять один раз', 'Спробували, пішли — і зв’язатися з ними вже не можна.'],
      ],
      howTitle: 'Як Loya допомагає грумінг-салонам',
      how: [
        ['🐾', 'Штамп-картка для улюбленців', '«Кожен 6-й грумінг зі знижкою 50%» — штамп ставиться телефоном за пару секунд.'],
        ['🔁', 'Нагадування про стрижку', 'Якщо клієнт не прийшов у звичний термін, лист іде сам: «Час освіжити шерсть?»'],
        ['🎁', '«Приведи друга»', 'Бонус за кожного нового клієнта з улюбленцем за рекомендацією.'],
        ['📊', 'Аналітика салону', 'Скільки постійних клієнтів, хто давно не був, коли пікові дні — усе на одному екрані.'],
      ],
      exampleTitle: 'Приклад',
      example: 'Салон обслуговує 200 улюбленців на місяць із середнім чеком €40. Якщо 10% клієнтів приходитимуть на один візит частіше, це близько €800 додаткової виручки на місяць.',
      faq: [
        ['Чи підійде для зоосалону з магазином?', 'Так. Можна вести і візити на грумінг, і покупки кормів — з накопичувальними бонусами.'],
        ['Як клієнт отримує картку?', 'За посиланням або QR на стійці: власник вводить ім’я й телефон, картка зберігається в Google Wallet чи Telegram.'],
        ['Якщо в клієнта кілька улюбленців?', 'Ведіть окрему картку на кожного улюбленця або одну спільну на власника — як зручніше вам.'],
      ],
    },
    sk: {
      name: 'Pre salóny pre zvieratá',
      metaTitle: 'Vernostný program pre psí salón a grooming — Loya',
      metaDesc: 'Pečiatková karta „každý 6. grooming so zľavou“, pripomienky ďalšieho strihania, „Priveď kamaráta“ a analytika pre psie salóny a grooming. 14 dní zadarmo.',
      h1: 'Vernostný program', h1gold: 'pre salóny pre zvieratá',
      lead: 'Miláčik potrebuje strihanie každých 6–8 týždňov. Loya zbadá, keď sa klient oneskorí, pripomenie návštevu a odmení ho za vernosť vášmu salónu.',
      painsTitle: 'Poznáte to?',
      pains: [
        ['🕒', 'Klienti zmeškajú termín', 'Je čas na strihanie, majiteľ zabudol — a objednal sa tam, kde to mal bližšie.'],
        ['📒', 'Objednávky v zošite', 'Nevidíte, kedy bol miláčik naposledy a kto patrí k najvernejším klientom.'],
        ['👋', 'Noví klienti prídu len raz', 'Vyskúšali, odišli — a kontaktovať ich už nemôžete.'],
      ],
      howTitle: 'Ako Loya pomáha salónom pre zvieratá',
      how: [
        ['🐾', 'Pečiatková karta pre miláčikov', '„Každý 6. grooming so zľavou 50 %“ — pečiatka telefónom za pár sekúnd.'],
        ['🔁', 'Pripomienka strihania', 'Ak klient nepríde v obvyklom čase, e-mail odíde sám: „Nie je čas na úpravu srsti?“'],
        ['🎁', '„Priveď kamaráta“', 'Bonus za každého nového klienta s miláčikom na odporúčanie.'],
        ['📊', 'Analytika salónu', 'Koľko je stálych klientov, kto dlho neprišiel, kedy sú najrušnejšie dni — všetko na jednej obrazovke.'],
      ],
      exampleTitle: 'Príklad',
      example: 'Salón obslúži 200 zvierat mesačne pri priemernej cene 40 €. Ak 10 % klientov príde o jednu návštevu častejšie, je to približne 800 € tržieb navyše mesačne.',
      faq: [
        ['Hodí sa pre salón s predajňou?', 'Áno. Môžete viesť návštevy na grooming aj nákupy krmiva — s bodovými bonusmi.'],
        ['Ako klient dostane kartu?', 'Cez odkaz alebo QR pri pulte: majiteľ zadá meno a telefón a karta sa uloží do Google Wallet alebo Telegramu.'],
        ['Čo ak má klient viac zvierat?', 'Veďte samostatnú kartu pre každé zviera alebo jednu spoločnú pre majiteľa — ako vám to vyhovuje.'],
      ],
    },
    en: {
      name: 'For pet grooming salons',
      metaTitle: 'Loyalty program for pet grooming salons — Loya',
      metaDesc: 'A stamp card (“every 6th groom half price”), reminders for the next groom, “Bring a friend” and analytics for pet grooming salons. 14 days free.',
      h1: 'Loyalty program', h1gold: 'for pet grooming salons',
      lead: 'Pets need a groom every 6–8 weeks. Loya notices when a client is running late, reminds them to book and rewards their loyalty to your salon.',
      painsTitle: 'Sound familiar?',
      pains: [
        ['🕒', 'Clients miss their usual time', 'It’s time for a groom, the owner forgot — and booked wherever was closer.'],
        ['📒', 'Bookings in a notebook', 'You can’t see when a pet was last in or who your most loyal clients are.'],
        ['👋', 'New clients come only once', 'They tried you, left — and you have no way to reach them.'],
      ],
      howTitle: 'How Loya helps grooming salons',
      how: [
        ['🐾', 'A stamp card for pets', '“Every 6th groom half price” — a stamp takes a couple of seconds with a phone.'],
        ['🔁', 'Groom reminders', 'If a client doesn’t come back at the usual time, an email goes out automatically: “Time for a fresh trim?”'],
        ['🎁', '“Bring a friend”', 'A bonus for every new client with a pet who comes on a recommendation.'],
        ['📊', 'Salon analytics', 'How many regulars you have, who hasn’t been in a while, which days are busiest — all on one screen.'],
      ],
      exampleTitle: 'Example',
      example: 'A salon grooms 200 pets a month at an average €40. If 10% of clients come in one extra time, that’s about €800 of extra revenue a month.',
      faq: [
        ['Does it work for a salon with a pet shop?', 'Yes. Track grooming visits and food purchases alike — with points rewards.'],
        ['How does a client get a card?', 'From a link or QR code at the desk: the owner enters a name and phone number, and the card is saved to Google Wallet or Telegram.'],
        ['What if a client has several pets?', 'Keep a separate card per pet or one shared card per owner — whichever suits you.'],
      ],
    },
  },
};
