// Тексты страниц под ниши (/cafe/, /beauty-salon/, /shop/ и их версии /ru/…, /uk/…, /sk/…).
// Собираются скриптом scripts/build-seo.js по шаблону scripts/niche.template.html.
module.exports = {
  cafe: {
    slug: 'cafe',
    icon: '☕',
    ru: {
      name: 'Для кафе и кофеен',
      metaTitle: 'Программа лояльности для кафе и кофейни — Loya',
      metaDesc: 'Электронная штамп-карта «каждый 10-й кофе бесплатно», сканер в телефоне бариста, автоматические рассылки и аналитика для кафе, кофеен и пекарен. 14 дней бесплатно.',
      h1: 'Программа лояльности', h1gold: 'для кафе и кофеен',
      lead: 'Электронная штамп-карта вместо бумажной: гость показывает QR, бариста сканирует его телефоном — и через неделю гость возвращается за следующей чашкой.',
      painsTitle: 'Знакомо?',
      pains: [
        ['🧾', 'Бумажные карточки теряются', 'Гости забывают карточки дома, а штампы легко подделать. Вы не знаете, кто ваш постоянный клиент.'],
        ['🕒', 'Пустые утренние и дневные часы', 'В час пик очередь, а после обеда пусто. Нечем позвать гостей в тихое время.'],
        ['👋', 'Новые гости не возвращаются', 'Человек зашёл один раз — и пропал. Связаться с ним уже нельзя.'],
      ],
      howTitle: 'Как Loya помогает кафе',
      how: [
        ['☕', 'Штамп-карта «10-й кофе бесплатно»', 'Настраивается за минуту: сколько штампов, какой подарок. Подарок система отмечает сама.'],
        ['📱', 'Телефон бариста — сканер', 'Откройте QR на экране кассы — телефон становится беспроводным сканером. Отметка за 2 секунды, очередь не растёт.'],
        ['⏰', 'Двойные штампы в тихие часы', 'Включите акцию на 14:00–17:00 — и гости сами начнут приходить в пустое время.'],
        ['💌', 'Автоматические письма', 'Гостю, который в шаге от подарка, пропал на месяц или празднует день рождения, письмо уходит само.'],
      ],
      exampleTitle: 'Пример',
      example: 'Кофейня на 600 гостей в месяц. Если с картой лояльности хотя бы 10% из них зайдут ещё по одному разу при среднем чеке €4, это около €240 дополнительной выручки в месяц — в 24 раза больше цены подписки.',
      faq: [
        ['Нужен ли гостю отдельное приложение?', 'Нет. Карта открывается по ссылке или QR и сохраняется в Google Wallet или Telegram. Можно и напечатать пластиковую карту с QR.'],
        ['Нужен ли специальный сканер?', 'Нет — подойдёт телефон любого сотрудника. Если у вас есть USB-сканер штрихкодов, он тоже работает.'],
        ['Подойдёт ли для пекарни или небольшой сети?', 'Да. Для нескольких точек есть тариф Pro: общая база, аналитика по каждой точке, сотрудники и роли.'],
      ],
    },
    uk: {
      name: 'Для кафе та кав’ярень',
      metaTitle: 'Програма лояльності для кафе та кав’ярні — Loya',
      metaDesc: 'Електронна штамп-картка «кожна 10-та кава безкоштовно», сканер у телефоні бариста, автоматичні розсилки й аналітика для кафе, кав’ярень і пекарень. 14 днів безкоштовно.',
      h1: 'Програма лояльності', h1gold: 'для кафе та кав’ярень',
      lead: 'Електронна штамп-картка замість паперової: гість показує QR, бариста сканує його телефоном — і за тиждень гість повертається по наступну чашку.',
      painsTitle: 'Знайомо?',
      pains: [
        ['🧾', 'Паперові картки губляться', 'Гості забувають картки вдома, а штампи легко підробити. Ви не знаєте, хто ваш постійний клієнт.'],
        ['🕒', 'Порожні ранкові й денні години', 'У годину пік черга, а після обіду порожньо. Нічим покликати гостей у тихий час.'],
        ['👋', 'Нові гості не повертаються', 'Людина зайшла один раз — і зникла. Зв’язатися з нею вже не можна.'],
      ],
      howTitle: 'Як Loya допомагає кафе',
      how: [
        ['☕', 'Штамп-картка «10-та кава безкоштовно»', 'Налаштовується за хвилину: скільки штампів, який подарунок. Подарунок система позначає сама.'],
        ['📱', 'Телефон бариста — сканер', 'Відкрийте QR на екрані каси — телефон стає бездротовим сканером. Позначка за 2 секунди, черга не росте.'],
        ['⏰', 'Подвійні штампи в тихі години', 'Увімкніть акцію на 14:00–17:00 — і гості самі почнуть приходити в порожній час.'],
        ['💌', 'Автоматичні листи', 'Гостю, якому лишився крок до подарунка, який зник на місяць або святкує день народження, лист іде сам.'],
      ],
      exampleTitle: 'Приклад',
      example: 'Кав’ярня на 600 гостей на місяць. Якщо з карткою лояльності хоча б 10% із них зайдуть ще по разу при середньому чеку €4, це близько €240 додаткової виручки на місяць — у 24 рази більше за ціну підписки.',
      faq: [
        ['Чи потрібен гостю окремий застосунок?', 'Ні. Картка відкривається за посиланням або QR і зберігається в Google Wallet чи Telegram. Можна й надрукувати пластикову картку з QR.'],
        ['Чи потрібен спеціальний сканер?', 'Ні — підійде телефон будь-якого працівника. Якщо у вас є USB-сканер штрихкодів, він теж працює.'],
        ['Чи підійде для пекарні або невеликої мережі?', 'Так. Для кількох точок є тариф Pro: спільна база, аналітика по кожній точці, працівники й ролі.'],
      ],
    },
    sk: {
      name: 'Pre kaviarne a kafé',
      metaTitle: 'Vernostný program pre kaviareň a kafé — Loya',
      metaDesc: 'Digitálna pečiatková karta „každá 10. káva zadarmo“, skener v telefóne baristu, automatické e-maily a analytika pre kaviarne, kafé a pekárne. 14 dní zadarmo.',
      h1: 'Vernostný program', h1gold: 'pre kaviarne a kafé',
      lead: 'Digitálna pečiatková karta namiesto papierovej: hosť ukáže QR, barista ho naskenuje telefónom — a o týždeň sa hosť vráti na ďalšiu šálku.',
      painsTitle: 'Poznáte to?',
      pains: [
        ['🧾', 'Papierové kartičky sa strácajú', 'Hostia ich nechávajú doma a pečiatky sa dajú ľahko sfalšovať. Neviete, kto je váš stály zákazník.'],
        ['🕒', 'Prázdne doobedie a popoludnie', 'Na špičke rad, po obede prázdno. Nemáte ako prilákať hostí v tichých hodinách.'],
        ['👋', 'Noví hostia sa nevracajú', 'Človek príde raz — a zmizne. Kontaktovať ho už nemôžete.'],
      ],
      howTitle: 'Ako Loya pomáha kaviarňam',
      how: [
        ['☕', 'Pečiatková karta „10. káva zadarmo“', 'Nastavíte za minútu: koľko pečiatok a aký darček. Darček systém vyznačí sám.'],
        ['📱', 'Telefón baristu ako skener', 'Otvorte QR na obrazovke pokladne — telefón sa zmení na bezdrôtový skener. Pečiatka za 2 sekundy, rad nerastie.'],
        ['⏰', 'Dvojité pečiatky v tichých hodinách', 'Zapnite akciu na 14:00–17:00 — a hostia začnú chodiť v čase, keď je prázdno.'],
        ['💌', 'Automatické e-maily', 'Hosťovi, ktorému chýba krok do darčeka, ktorý mesiac neprišiel alebo má narodeniny, odíde e-mail sám.'],
      ],
      exampleTitle: 'Príklad',
      example: 'Kaviareň so 600 hosťami mesačne. Ak s vernostnou kartou príde aspoň 10 % z nich ešte raz pri priemernom účte 4 €, je to približne 240 € tržieb navyše mesačne — 24-krát viac než cena predplatného.',
      faq: [
        ['Potrebuje hosť samostatnú aplikáciu?', 'Nie. Karta sa otvorí cez odkaz alebo QR a uloží sa do Google Wallet alebo Telegramu. Dá sa aj vytlačiť plastová karta s QR.'],
        ['Potrebujem špeciálny skener?', 'Nie — stačí telefón ktoréhokoľvek zamestnanca. Funguje aj USB skener čiarových kódov, ak ho máte.'],
        ['Hodí sa pre pekáreň alebo malú sieť?', 'Áno. Pre viac prevádzok je tarif Pro: spoločná databáza, analytika pre každú prevádzku, zamestnanci a roly.'],
      ],
    },
    en: {
      name: 'For cafés & coffee shops',
      metaTitle: 'Loyalty program for cafés and coffee shops — Loya',
      metaDesc: 'A digital stamp card (“every 10th coffee free”), a scanner on the barista’s phone, automated emails and analytics for cafés, coffee shops and bakeries. 14 days free.',
      h1: 'Loyalty program', h1gold: 'for cafés & coffee shops',
      lead: 'A digital stamp card instead of a paper one: the guest shows a QR code, the barista scans it with a phone — and a week later the guest is back for the next cup.',
      painsTitle: 'Sound familiar?',
      pains: [
        ['🧾', 'Paper cards get lost', 'Guests leave them at home and stamps are easy to fake. You don’t know who your regulars are.'],
        ['🕒', 'Empty mid-morning and afternoon hours', 'There’s a queue at peak time and nobody after lunch — and no way to bring guests in during quiet hours.'],
        ['👋', 'New guests don’t come back', 'Someone visits once and disappears. You have no way to reach them.'],
      ],
      howTitle: 'How Loya helps cafés',
      how: [
        ['☕', '“10th coffee free” stamp card', 'Set it up in a minute: how many stamps and what reward. The reward is tracked automatically.'],
        ['📱', 'The barista’s phone is the scanner', 'Open the QR on the till screen and any phone becomes a wireless scanner. A stamp takes 2 seconds — the queue doesn’t grow.'],
        ['⏰', 'Double stamps in quiet hours', 'Turn on a 2–5 pm promo and guests start coming when it’s empty.'],
        ['💌', 'Automated emails', 'Guests one step from a reward, missing for a month or celebrating a birthday get an email automatically.'],
      ],
      exampleTitle: 'Example',
      example: 'A coffee shop with 600 guests a month. If the loyalty card brings just 10% of them back one extra time at an average €4 purchase, that’s about €240 of extra revenue a month — 24 times the subscription price.',
      faq: [
        ['Do guests need to install an app?', 'No. The card opens from a link or QR code and is saved to Google Wallet or Telegram. You can also print plastic cards with a QR code.'],
        ['Do I need a special scanner?', 'No — any staff member’s phone works. A USB barcode scanner works too if you have one.'],
        ['Does it work for a bakery or a small chain?', 'Yes. For several locations there’s the Pro plan: a shared database, per-location analytics, staff and roles.'],
      ],
    },
  },

  beauty: {
    slug: 'beauty-salon',
    icon: '💅',
    ru: {
      name: 'Для салонов красоты и барбершопов',
      metaTitle: 'Программа лояльности для салона красоты и барбершопа — Loya',
      metaDesc: 'Карты лояльности, напоминания о повторном визите, «Приведи подругу», поздравления с днём рождения и аналитика для салонов красоты, барбершопов, СПА и маникюра. 14 дней бесплатно.',
      h1: 'Программа лояльности', h1gold: 'для салонов красоты и барбершопов',
      lead: 'Клиент возвращается к своему мастеру не по памяти, а потому что вовремя получил напоминание и знает, что его ждёт бонус.',
      painsTitle: 'Знакомо?',
      pains: [
        ['📅', 'Клиенты пропадают между визитами', 'Человек стригся у вас два месяца назад и, возможно, уже ходит к другому мастеру.'],
        ['📒', 'База клиентов в блокноте или мессенджере', 'Нет истории визитов, не видно, кто ваш лучший клиент и кто давно не приходил.'],
        ['📣', 'Сарафанное радио работает само по себе', 'Клиенты рекомендуют вас друзьям, но это никак не поощряется и не считается.'],
      ],
      howTitle: 'Как Loya помогает салонам',
      how: [
        ['💳', 'Скидочная или накопительная карта', 'Процент скидки или бонус после нужной суммы — выберите то, что подходит вашим услугам.'],
        ['🔁', 'Возврат пропавших клиентов', 'Тем, кто давно не был, письмо уходит само — с поводом записаться снова.'],
        ['🎁', '«Приведи подругу» и день рождения', 'Бонус за рекомендацию и поздравление в день рождения — автоматически, без ручных напоминаний.'],
        ['👩‍🎨', 'Мастера и права доступа', 'У каждого мастера свой PIN. Видно, кто сколько клиентов обслужил.'],
      ],
      exampleTitle: 'Пример',
      example: 'Салон на 300 клиентов в месяц со средним чеком €30. Если 10% клиентов придут на один визит больше, это около €900 дополнительной выручки в месяц.',
      faq: [
        ['Подойдёт ли для барбершопа или ногтевой студии?', 'Да. Loya работает для любых услуг: стрижки, маникюр, косметология, массаж, СПА.'],
        ['Как клиенты получают карту?', 'По ссылке или QR на ресепшене: клиент вводит имя и телефон, а карта сохраняется в Google Wallet или Telegram.'],
        ['Можно ли просить отзывы?', 'Да, после визита можно автоматически отправлять просьбу оставить отзыв.'],
      ],
    },
    uk: {
      name: 'Для салонів краси та барбершопів',
      metaTitle: 'Програма лояльності для салону краси та барбершопу — Loya',
      metaDesc: 'Картки лояльності, нагадування про повторний візит, «Приведи подругу», привітання з днем народження й аналітика для салонів краси, барбершопів, СПА й манікюру. 14 днів безкоштовно.',
      h1: 'Програма лояльності', h1gold: 'для салонів краси та барбершопів',
      lead: 'Клієнт повертається до свого майстра не з пам’яті, а тому що вчасно отримав нагадування й знає, що на нього чекає бонус.',
      painsTitle: 'Знайомо?',
      pains: [
        ['📅', 'Клієнти зникають між візитами', 'Людина стриглася у вас два місяці тому і, можливо, вже ходить до іншого майстра.'],
        ['📒', 'База клієнтів у блокноті чи месенджері', 'Немає історії візитів, не видно, хто ваш найкращий клієнт і хто давно не приходив.'],
        ['📣', 'Сарафанне радіо працює саме по собі', 'Клієнти радять вас друзям, але це ніяк не заохочується й не рахується.'],
      ],
      howTitle: 'Як Loya допомагає салонам',
      how: [
        ['💳', 'Знижкова або накопичувальна картка', 'Відсоток знижки або бонус після потрібної суми — оберіть те, що пасує вашим послугам.'],
        ['🔁', 'Повернення зниклих клієнтів', 'Тим, хто давно не був, лист іде сам — із приводом записатися знову.'],
        ['🎁', '«Приведи подругу» й день народження', 'Бонус за рекомендацію й привітання в день народження — автоматично, без ручних нагадувань.'],
        ['👩‍🎨', 'Майстри та права доступу', 'У кожного майстра свій PIN. Видно, хто скільки клієнтів обслужив.'],
      ],
      exampleTitle: 'Приклад',
      example: 'Салон на 300 клієнтів на місяць із середнім чеком €30. Якщо 10% клієнтів прийдуть на один візит більше, це близько €900 додаткової виручки на місяць.',
      faq: [
        ['Чи підійде для барбершопу або нігтьової студії?', 'Так. Loya працює для будь-яких послуг: стрижки, манікюр, косметологія, масаж, СПА.'],
        ['Як клієнти отримують картку?', 'За посиланням або QR на рецепції: клієнт вводить ім’я й телефон, а картка зберігається в Google Wallet чи Telegram.'],
        ['Чи можна просити відгуки?', 'Так, після візиту можна автоматично надсилати прохання залишити відгук.'],
      ],
    },
    sk: {
      name: 'Pre kozmetické salóny a barbershopy',
      metaTitle: 'Vernostný program pre kozmetický salón a barbershop — Loya',
      metaDesc: 'Vernostné karty, pripomienky ďalšej návštevy, „Priveď kamarátku“, blahoželania k narodeninám a analytika pre kozmetické salóny, barbershopy, SPA a nechtové štúdiá. 14 dní zadarmo.',
      h1: 'Vernostný program', h1gold: 'pre salóny krásy a barbershopy',
      lead: 'Zákazník sa k svojmu majstrovi vracia nie náhodou, ale preto, že včas dostal pripomienku a vie, že ho čaká bonus.',
      painsTitle: 'Poznáte to?',
      pains: [
        ['📅', 'Zákazníci sa medzi návštevami strácajú', 'Človek bol u vás pred dvoma mesiacmi a možno už chodí k inému majstrovi.'],
        ['📒', 'Zákazníci v zošite alebo v messengeri', 'Žiadna história návštev — nevidíte, kto je váš najlepší zákazník a kto dlho neprišiel.'],
        ['📣', 'Odporúčania fungujú samy od seba', 'Zákazníci vás odporúčajú priateľom, no nič ich k tomu nemotivuje a nikto to nepočíta.'],
      ],
      howTitle: 'Ako Loya pomáha salónom',
      how: [
        ['💳', 'Zľavová alebo bodová karta', 'Percento zľavy alebo bonus po dosiahnutí sumy — vyberte, čo sa hodí k vašim službám.'],
        ['🔁', 'Návrat stratených zákazníkov', 'Tým, ktorí dlho neprišli, odíde e-mail sám — s dôvodom znova sa objednať.'],
        ['🎁', '„Priveď kamarátku“ a narodeniny', 'Bonus za odporúčanie a blahoželanie k narodeninám — automaticky, bez ručného pripomínania.'],
        ['👩‍🎨', 'Majstri a prístupové práva', 'Každý majster má vlastný PIN. Vidíte, kto koľko zákazníkov obslúžil.'],
      ],
      exampleTitle: 'Príklad',
      example: 'Salón s 300 zákazníkmi mesačne a priemerným účtom 30 €. Ak 10 % zákazníkov príde o jednu návštevu viac, je to približne 900 € tržieb navyše mesačne.',
      faq: [
        ['Hodí sa pre barbershop alebo nechtové štúdio?', 'Áno. Loya funguje pre akékoľvek služby: strihanie, manikúru, kozmetiku, masáže, SPA.'],
        ['Ako zákazníci dostanú kartu?', 'Cez odkaz alebo QR na recepcii: zákazník zadá meno a telefón a karta sa uloží do Google Wallet alebo Telegramu.'],
        ['Môžem žiadať o recenzie?', 'Áno, po návšteve môžete automaticky posielať prosbu o recenziu.'],
      ],
    },
    en: {
      name: 'For beauty salons & barbershops',
      metaTitle: 'Loyalty program for beauty salons and barbershops — Loya',
      metaDesc: 'Loyalty cards, repeat-visit reminders, “Bring a friend”, birthday greetings and analytics for beauty salons, barbershops, spas and nail studios. 14 days free.',
      h1: 'Loyalty program', h1gold: 'for beauty salons & barbershops',
      lead: 'Clients return to their stylist not by chance, but because they got a reminder at the right time and know a bonus is waiting.',
      painsTitle: 'Sound familiar?',
      pains: [
        ['📅', 'Clients drift away between visits', 'Someone had a haircut with you two months ago and may already be seeing another stylist.'],
        ['📒', 'Clients in a notebook or a messenger', 'No visit history — you can’t see who your best clients are or who hasn’t been back.'],
        ['📣', 'Word of mouth goes unrewarded', 'Clients recommend you to friends, but nothing rewards it and nobody keeps track.'],
      ],
      howTitle: 'How Loya helps salons',
      how: [
        ['💳', 'Discount or points card', 'A percentage discount or a bonus after a set amount — pick what fits your services.'],
        ['🔁', 'Win back lost clients', 'Clients who haven’t visited in a while get an email automatically, with a reason to book again.'],
        ['🎁', '“Bring a friend” and birthdays', 'A referral bonus and a birthday greeting — automatic, no manual reminders.'],
        ['👩‍🎨', 'Stylists and access rights', 'Every stylist has their own PIN. You see who served how many clients.'],
      ],
      exampleTitle: 'Example',
      example: 'A salon with 300 clients a month and an average ticket of €30. If 10% of clients come back for one extra visit, that’s about €900 of extra revenue a month.',
      faq: [
        ['Does it work for a barbershop or nail studio?', 'Yes. Loya works for any service: haircuts, nails, cosmetics, massage, spa.'],
        ['How do clients get a card?', 'From a link or a QR code at the front desk: the client enters a name and phone number, and the card is saved to Google Wallet or Telegram.'],
        ['Can I ask for reviews?', 'Yes — after a visit, a review request can be sent automatically.'],
      ],
    },
  },

  shop: {
    slug: 'shop',
    icon: '🛍️',
    ru: {
      name: 'Для магазинов',
      metaTitle: 'Программа лояльности для магазина — Loya',
      metaDesc: 'Накопительные и скидочные карты, бонусы после нужной суммы, товары и склад, рассылки и аналитика покупок для небольших магазинов одежды, косметики, цветов и подарков. 14 дней бесплатно.',
      h1: 'Программа лояльности', h1gold: 'для магазина',
      lead: 'Покупатель видит свои бонусы в телефоне, получает письмо о новинках и приходит снова — к вам, а не к соседнему магазину или маркетплейсу.',
      painsTitle: 'Знакомо?',
      pains: [
        ['🛒', 'Покупатели уходят на маркетплейсы', 'Цена везде похожая — и у человека нет причины возвращаться именно к вам.'],
        ['🤷', 'Вы не знаете своих покупателей', 'Кто покупает чаще, на какую сумму и когда приходил в последний раз — непонятно.'],
        ['📦', 'Акции и новинки никто не видит', 'Объявление в соцсетях увидели не те, кто реально у вас покупает.'],
      ],
      howTitle: 'Как Loya помогает магазинам',
      how: [
        ['💰', 'Накопительная карта с бонусом', 'Бонус или подарок после нужной суммы покупок — покупатель видит, сколько осталось.'],
        ['🧾', 'Товары, склад и чеки', 'В тарифе Starter — товары, остатки и чеки из кассы, привязанные к карте покупателя.'],
        ['💌', 'Рассылки своим покупателям', 'Email и Telegram с готовыми текстами: новинки, распродажа, «давно не заходили».'],
        ['📊', 'Аналитика покупок', 'Выручка, средний чек, воронка лояльности и тепловая карта — когда приходят и когда запускать акции.'],
      ],
      exampleTitle: 'Пример',
      example: 'Магазин на 400 покупателей в месяц со средним чеком €25. Если 10% из них сделают одну покупку больше, это около €1000 дополнительной выручки в месяц.',
      faq: [
        ['Подойдёт ли для магазина одежды, косметики или цветов?', 'Да. Loya подходит для любой розницы, где покупатели возвращаются: одежда, косметика, цветы, подарки, зоотовары.'],
        ['Работает ли с кассой?', 'Можно подключить чеки из кассы через POS-ключ, а можно отмечать покупки вручную или сканером.'],
        ['Если у меня несколько магазинов?', 'Для нескольких точек есть тариф Pro: общая база, аналитика по каждой точке и общий обмен данными между компьютерами.'],
      ],
    },
    uk: {
      name: 'Для магазинів',
      metaTitle: 'Програма лояльності для магазину — Loya',
      metaDesc: 'Накопичувальні та знижкові картки, бонуси після потрібної суми, товари й склад, розсилки й аналітика покупок для невеликих магазинів одягу, косметики, квітів і подарунків. 14 днів безкоштовно.',
      h1: 'Програма лояльності', h1gold: 'для магазину',
      lead: 'Покупець бачить свої бонуси в телефоні, отримує лист про новинки й приходить знову — до вас, а не до сусіднього магазину чи маркетплейсу.',
      painsTitle: 'Знайомо?',
      pains: [
        ['🛒', 'Покупці йдуть на маркетплейси', 'Ціна скрізь схожа — і в людини немає причини повертатися саме до вас.'],
        ['🤷', 'Ви не знаєте своїх покупців', 'Хто купує частіше, на яку суму й коли приходив востаннє — незрозуміло.'],
        ['📦', 'Акції й новинки ніхто не бачить', 'Оголошення в соцмережах побачили не ті, хто справді у вас купує.'],
      ],
      howTitle: 'Як Loya допомагає магазинам',
      how: [
        ['💰', 'Накопичувальна картка з бонусом', 'Бонус або подарунок після потрібної суми покупок — покупець бачить, скільки лишилося.'],
        ['🧾', 'Товари, склад і чеки', 'У тарифі Starter — товари, залишки й чеки з каси, прив’язані до картки покупця.'],
        ['💌', 'Розсилки своїм покупцям', 'Email і Telegram із готовими текстами: новинки, розпродаж, «давно не заходили».'],
        ['📊', 'Аналітика покупок', 'Виручка, середній чек, воронка лояльності й теплова карта — коли приходять і коли запускати акції.'],
      ],
      exampleTitle: 'Приклад',
      example: 'Магазин на 400 покупців на місяць із середнім чеком €25. Якщо 10% із них зроблять одну покупку більше, це близько €1000 додаткової виручки на місяць.',
      faq: [
        ['Чи підійде для магазину одягу, косметики чи квітів?', 'Так. Loya пасує будь-якій роздрібній торгівлі, куди покупці повертаються: одяг, косметика, квіти, подарунки, зоотовари.'],
        ['Чи працює з касою?', 'Можна підключити чеки з каси через POS-ключ, а можна позначати покупки вручну чи сканером.'],
        ['Якщо в мене кілька магазинів?', 'Для кількох точок є тариф Pro: спільна база, аналітика по кожній точці й спільний обмін даними між комп’ютерами.'],
      ],
    },
    sk: {
      name: 'Pre obchody',
      metaTitle: 'Vernostný program pre obchod — Loya',
      metaDesc: 'Bodové a zľavové karty, bonusy po dosiahnutí sumy, tovar a sklad, kampane a analytika nákupov pre malé obchody s oblečením, kozmetikou, kvetmi a darčekmi. 14 dní zadarmo.',
      h1: 'Vernostný program', h1gold: 'pre obchody',
      lead: 'Zákazník vidí svoje bonusy v telefóne, dostane e-mail o novinkách a príde znova — k vám, nie do susedného obchodu ani na marketplace.',
      painsTitle: 'Poznáte to?',
      pains: [
        ['🛒', 'Zákazníci odchádzajú na marketplace', 'Cena je všade podobná — a človek nemá dôvod vracať sa práve k vám.'],
        ['🤷', 'Svojich zákazníkov nepoznáte', 'Kto nakupuje častejšie, za koľko a kedy bol naposledy — netušíte.'],
        ['📦', 'Akcie a novinky nikto nevidí', 'Príspevok na sociálnych sieťach videli iní ľudia než tí, ktorí u vás naozaj nakupujú.'],
      ],
      howTitle: 'Ako Loya pomáha obchodom',
      how: [
        ['💰', 'Bodová karta s bonusom', 'Bonus alebo darček po dosiahnutí sumy nákupov — zákazník vidí, koľko mu zostáva.'],
        ['🧾', 'Tovar, sklad a účtenky', 'V tarife Starter — tovar, zásoby a účtenky z pokladne priradené ku karte zákazníka.'],
        ['💌', 'Kampane pre vlastných zákazníkov', 'E-mail a Telegram s hotovými textami: novinky, výpredaj, „dlho ste u nás neboli“.'],
        ['📊', 'Analytika nákupov', 'Tržby, priemerný nákup, vernostný lievik a teplotná mapa — kedy zákazníci chodia a kedy spustiť akciu.'],
      ],
      exampleTitle: 'Príklad',
      example: 'Obchod so 400 zákazníkmi mesačne a priemerným nákupom 25 €. Ak 10 % z nich nakúpi ešte raz, je to približne 1000 € tržieb navyše mesačne.',
      faq: [
        ['Hodí sa pre obchod s oblečením, kozmetikou alebo kvetmi?', 'Áno. Loya sa hodí pre akýkoľvek maloobchod, kam sa zákazníci vracajú: oblečenie, kozmetika, kvety, darčeky, chovateľské potreby.'],
        ['Funguje s pokladňou?', 'Účtenky z pokladne môžete pripojiť cez POS kľúč, alebo nákupy zaznamenávať ručne či skenerom.'],
        ['Čo ak mám viac obchodov?', 'Pre viac prevádzok je tarif Pro: spoločná databáza, analytika pre každú prevádzku a spoločná výmena údajov medzi počítačmi.'],
      ],
    },
    en: {
      name: 'For shops',
      metaTitle: 'Loyalty program for retail shops — Loya',
      metaDesc: 'Points and discount cards, rewards after a set amount, products and stock, campaigns and purchase analytics for small clothing, cosmetics, flower and gift shops. 14 days free.',
      h1: 'Loyalty program', h1gold: 'for retail shops',
      lead: 'Customers see their rewards on their phone, get an email about new arrivals and come back — to you, not to the shop next door or a marketplace.',
      painsTitle: 'Sound familiar?',
      pains: [
        ['🛒', 'Customers drift to marketplaces', 'Prices are similar everywhere — so there’s no reason to come back to you in particular.'],
        ['🤷', 'You don’t know your customers', 'Who buys most often, how much, and when they last visited — it’s all a guess.'],
        ['📦', 'Nobody sees your promos and new arrivals', 'Your social media post reached people other than the ones who actually buy from you.'],
      ],
      howTitle: 'How Loya helps shops',
      how: [
        ['💰', 'Points card with a reward', 'A bonus or gift after a set amount spent — customers see how much is left.'],
        ['🧾', 'Products, stock and receipts', 'The Starter plan includes products, stock levels and till receipts linked to the customer’s card.'],
        ['💌', 'Campaigns to your own customers', 'Email and Telegram with ready-made texts: new arrivals, sales, “we haven’t seen you in a while”.'],
        ['📊', 'Purchase analytics', 'Revenue, average purchase, loyalty funnel and a heatmap — when customers come and when to run promotions.'],
      ],
      exampleTitle: 'Example',
      example: 'A shop with 400 customers a month and an average purchase of €25. If 10% of them make one extra purchase, that’s about €1,000 of extra revenue a month.',
      faq: [
        ['Does it work for clothing, cosmetics or flower shops?', 'Yes. Loya fits any retail business where customers come back: clothing, cosmetics, flowers, gifts, pet supplies.'],
        ['Does it work with my till?', 'You can connect till receipts with a POS key, or record purchases manually or with a scanner.'],
        ['What if I have several shops?', 'For several locations there’s the Pro plan: a shared database, per-location analytics and data sync between computers.'],
      ],
    },
  },
};
