// Дополнительные тексты админки (безопасность, деньги, внимание, карточка клиента, журнал) — на 4 языках.
// Подмешиваются к основному словарю в _x_admin_page.js.
module.exports = {
  ru: {
    code: 'Код из приложения (6 цифр)', needCode: 'Введите 6-значный код из приложения-аутентификатора', badCode: 'Неверный код — проверьте время на телефоне',
    logoutAll: 'Выйти на всех устройствах', confirmLogoutAll: 'Завершить все сеансы админки, включая этот?',
    secTitle: '🛡 Безопасность', tfaOn: 'Вход по паролю + коду из приложения включён', tfaOff: 'Двухфакторный вход выключен — пароль единственная защита', tfaSetup: 'Включить',
    tfaStep1: '1. Откройте Google Authenticator, Microsoft Authenticator или 1Password и отсканируйте QR-код (или введите секрет вручную).',
    tfaStep2: '2. Введите код из приложения, чтобы проверить:', tfaTest: 'Проверить код', tfaTestOk: '✅ Код верный.',
    tfaStep3: (s) => `3. В Vercel → Settings → Environment Variables добавьте ADMIN_TOTP_SECRET = ${s} и нажмите Redeploy. После этого при входе будет нужен код. Сохраните секрет в надёжном месте.`,
    settingsMissing: 'Нет таблиц admin_log / admin_settings — выполните последний блок schema.sql в Supabase. Без них не работают журнал и «Выйти на всех устройствах».',
    mTitle: '💶 Деньги', mMrr: 'Доход в месяц (MRR)', mArr: 'В год (ARR)', mPaying: 'Платящих (Starter / Pro)', mConv: 'Пробный → платный',
    mConvNote: (a, b) => `${a} из ${b} завершённых пробных`, mChart: 'Новые подписки и отмены за 12 месяцев', mNew: 'новые', mCancel: 'отмены',
    mNote: 'Только боевые оплаты. Цены: Starter €9.99, Pro €19.99. Отмены — по месяцу последнего изменения.',
    attTitle: '🔔 Требуют внимания', attPast: 'Проблема с оплатой', attTrial: 'Пробный заканчивается в ближайшие 3 дня', attSilent: 'Платят, но не выходили на связь 14+ дней', attNone: 'Всё спокойно — никого не нужно догонять.',
    open: 'Открыть', cTitle: 'Карточка клиента', cKeys: 'Все ключи с этим email', cLogins: 'Входы в кабинет владельца', cRegs: 'Онлайн-регистраций гостей', cMail: 'Писем за 30 дней',
    cProfile: 'Страница бизнеса', cNoLogins: 'Входов в кабинет не было', cFromTrial: 'начинал с пробного', cSub: 'Подписка Stripe', cNoSub: 'нет', cYes: 'есть',
    extend: '+ Продлить пробный', extendAsk: 'На сколько дней продлить пробный период? (1–90)', resend: '✉ Отправить ключ на почту', resent: 'Письмо с ключом отправлено',
    cancelSub: 'Отменить подписку Stripe', cancelEnd: 'В конце оплаченного периода', cancelNow: 'Немедленно',
    confirmCancelNow: 'Отменить подписку в Stripe немедленно? Деньги за остаток периода автоматически не вернутся.', confirmCancelEnd: 'Отменить подписку в конце оплаченного периода? До этого клиент пользуется как обычно.',
    canceledOk: 'Подписка отменена', close: 'Закрыть', done: 'Готово', stripeErr: (d) => 'Ошибка Stripe: ' + d, noSub: 'У этого ключа нет подписки Stripe', mailErr: 'Не удалось отправить письмо — проверьте почту в «Готовности к запуску»',
    jTitle: '🧾 Журнал действий', jEmpty: 'Пока пусто', jShow: 'Показать', jHide: 'Скрыть', jMissing: 'Журнал появится после создания таблицы admin_log',
    op_login: 'вход в админку', op_login_fail: 'неудачный вход', op_ban: 'блокировка', op_unban: 'разблокировка', op_make_free: 'сделан бесплатным', op_make_paid: 'возвращён платным',
    op_note: 'заметка', op_set_tier: 'смена тарифа', op_end_trial: 'пробный завершён', op_extend_trial: 'пробный продлён', op_create_free: 'выдан бесплатный доступ', op_delete: 'удаление',
    op_resend_key: 'ключ отправлен на почту', op_cancel_stripe: 'отмена подписки', op_logout_all: 'выход на всех устройствах', details: 'Подробнее',
  },
  uk: {
    code: 'Код із застосунку (6 цифр)', needCode: 'Введіть 6-значний код із застосунку-автентифікатора', badCode: 'Невірний код — перевірте час на телефоні',
    logoutAll: 'Вийти на всіх пристроях', confirmLogoutAll: 'Завершити всі сеанси адмінки, включно з цим?',
    secTitle: '🛡 Безпека', tfaOn: 'Вхід за паролем + кодом із застосунку увімкнено', tfaOff: 'Двофакторний вхід вимкнено — пароль єдиний захист', tfaSetup: 'Увімкнути',
    tfaStep1: '1. Відкрийте Google Authenticator, Microsoft Authenticator або 1Password і відскануйте QR-код (або введіть секрет вручну).',
    tfaStep2: '2. Введіть код із застосунку, щоб перевірити:', tfaTest: 'Перевірити код', tfaTestOk: '✅ Код правильний.',
    tfaStep3: (s) => `3. У Vercel → Settings → Environment Variables додайте ADMIN_TOTP_SECRET = ${s} і натисніть Redeploy. Після цього під час входу знадобиться код. Збережіть секрет у надійному місці.`,
    settingsMissing: 'Немає таблиць admin_log / admin_settings — виконайте останній блок schema.sql у Supabase. Без них не працюють журнал і «Вийти на всіх пристроях».',
    mTitle: '💶 Гроші', mMrr: 'Дохід на місяць (MRR)', mArr: 'На рік (ARR)', mPaying: 'Платять (Starter / Pro)', mConv: 'Пробний → платний',
    mConvNote: (a, b) => `${a} з ${b} завершених пробних`, mChart: 'Нові підписки й скасування за 12 місяців', mNew: 'нові', mCancel: 'скасування',
    mNote: 'Лише бойові оплати. Ціни: Starter €9.99, Pro €19.99. Скасування — за місяцем останньої зміни.',
    attTitle: '🔔 Потребують уваги', attPast: 'Проблема з оплатою', attTrial: 'Пробний закінчується найближчі 3 дні', attSilent: 'Платять, але не виходили на зв’язок 14+ днів', attNone: 'Усе спокійно — нікого не треба наздоганяти.',
    open: 'Відкрити', cTitle: 'Картка клієнта', cKeys: 'Усі ключі з цим email', cLogins: 'Входи в кабінет власника', cRegs: 'Онлайн-реєстрацій гостей', cMail: 'Листів за 30 днів',
    cProfile: 'Сторінка бізнесу', cNoLogins: 'Входів у кабінет не було', cFromTrial: 'починав із пробного', cSub: 'Підписка Stripe', cNoSub: 'немає', cYes: 'є',
    extend: '+ Продовжити пробний', extendAsk: 'На скільки днів продовжити пробний період? (1–90)', resend: '✉ Надіслати ключ на пошту', resent: 'Лист із ключем надіслано',
    cancelSub: 'Скасувати підписку Stripe', cancelEnd: 'Наприкінці оплаченого періоду', cancelNow: 'Негайно',
    confirmCancelNow: 'Скасувати підписку в Stripe негайно? Гроші за решту періоду автоматично не повернуться.', confirmCancelEnd: 'Скасувати підписку наприкінці оплаченого періоду? До того клієнт користується як зазвичай.',
    canceledOk: 'Підписку скасовано', close: 'Закрити', done: 'Готово', stripeErr: (d) => 'Помилка Stripe: ' + d, noSub: 'У цього ключа немає підписки Stripe', mailErr: 'Не вдалося надіслати лист — перевірте пошту в «Готовності до запуску»',
    jTitle: '🧾 Журнал дій', jEmpty: 'Поки порожньо', jShow: 'Показати', jHide: 'Сховати', jMissing: 'Журнал з’явиться після створення таблиці admin_log',
    op_login: 'вхід в адмінку', op_login_fail: 'невдалий вхід', op_ban: 'блокування', op_unban: 'розблокування', op_make_free: 'зроблено безкоштовним', op_make_paid: 'повернено платним',
    op_note: 'нотатка', op_set_tier: 'зміна тарифу', op_end_trial: 'пробний завершено', op_extend_trial: 'пробний продовжено', op_create_free: 'видано безкоштовний доступ', op_delete: 'видалення',
    op_resend_key: 'ключ надіслано на пошту', op_cancel_stripe: 'скасування підписки', op_logout_all: 'вихід на всіх пристроях', details: 'Докладніше',
  },
  sk: {
    code: 'Kód z aplikácie (6 číslic)', needCode: 'Zadajte 6-miestny kód z overovacej aplikácie', badCode: 'Nesprávny kód — skontrolujte čas v telefóne',
    logoutAll: 'Odhlásiť na všetkých zariadeniach', confirmLogoutAll: 'Ukončiť všetky relácie administrácie vrátane tejto?',
    secTitle: '🛡 Bezpečnosť', tfaOn: 'Prihlásenie heslom + kódom z aplikácie je zapnuté', tfaOff: 'Dvojfaktorové prihlásenie je vypnuté — jedinou ochranou je heslo', tfaSetup: 'Zapnúť',
    tfaStep1: '1. Otvorte Google Authenticator, Microsoft Authenticator alebo 1Password a naskenujte QR kód (alebo zadajte tajomstvo ručne).',
    tfaStep2: '2. Na overenie zadajte kód z aplikácie:', tfaTest: 'Overiť kód', tfaTestOk: '✅ Kód je správny.',
    tfaStep3: (s) => `3. Vo Vercel → Settings → Environment Variables pridajte ADMIN_TOTP_SECRET = ${s} a stlačte Redeploy. Potom bude pri prihlásení potrebný kód. Tajomstvo si uložte na bezpečné miesto.`,
    settingsMissing: 'Chýbajú tabuľky admin_log / admin_settings — spustite posledný blok schema.sql v Supabase. Bez nich nefunguje denník ani „Odhlásiť na všetkých zariadeniach“.',
    mTitle: '💶 Peniaze', mMrr: 'Príjem za mesiac (MRR)', mArr: 'Za rok (ARR)', mPaying: 'Platiacich (Starter / Pro)', mConv: 'Skúšobná → platená',
    mConvNote: (a, b) => `${a} z ${b} ukončených skúšobných`, mChart: 'Nové predplatné a zrušenia za 12 mesiacov', mNew: 'nové', mCancel: 'zrušenia',
    mNote: 'Len ostré platby. Ceny: Starter 9,99 €, Pro 19,99 €. Zrušenia podľa mesiaca poslednej zmeny.',
    attTitle: '🔔 Vyžadujú pozornosť', attPast: 'Problém s platbou', attTrial: 'Skúšobná doba končí do 3 dní', attSilent: 'Platia, ale 14+ dní sa neozvali', attNone: 'Všetko v poriadku — nikoho netreba doháňať.',
    open: 'Otvoriť', cTitle: 'Karta klienta', cKeys: 'Všetky kľúče s týmto e-mailom', cLogins: 'Prihlásenia do účtu majiteľa', cRegs: 'Online registrácií hostí', cMail: 'E-mailov za 30 dní',
    cProfile: 'Stránka podniku', cNoLogins: 'Do účtu sa zatiaľ neprihlásil', cFromTrial: 'začínal skúšobnou', cSub: 'Predplatné Stripe', cNoSub: 'nie', cYes: 'áno',
    extend: '+ Predĺžiť skúšobnú', extendAsk: 'O koľko dní predĺžiť skúšobnú dobu? (1–90)', resend: '✉ Poslať kľúč e-mailom', resent: 'E-mail s kľúčom odoslaný',
    cancelSub: 'Zrušiť predplatné Stripe', cancelEnd: 'Na konci zaplateného obdobia', cancelNow: 'Okamžite',
    confirmCancelNow: 'Zrušiť predplatné v Stripe okamžite? Peniaze za zvyšok obdobia sa automaticky nevrátia.', confirmCancelEnd: 'Zrušiť predplatné na konci zaplateného obdobia? Dovtedy klient používa program normálne.',
    canceledOk: 'Predplatné zrušené', close: 'Zavrieť', done: 'Hotovo', stripeErr: (d) => 'Chyba Stripe: ' + d, noSub: 'Tento kľúč nemá predplatné Stripe', mailErr: 'E-mail sa nepodarilo odoslať — skontrolujte e-mail v „Pripravenosti“',
    jTitle: '🧾 Denník akcií', jEmpty: 'Zatiaľ prázdne', jShow: 'Zobraziť', jHide: 'Skryť', jMissing: 'Denník sa zobrazí po vytvorení tabuľky admin_log',
    op_login: 'prihlásenie', op_login_fail: 'neúspešné prihlásenie', op_ban: 'zablokovanie', op_unban: 'odblokovanie', op_make_free: 'nastavené zadarmo', op_make_paid: 'vrátené na platené',
    op_note: 'poznámka', op_set_tier: 'zmena tarifu', op_end_trial: 'skúšobná ukončená', op_extend_trial: 'skúšobná predĺžená', op_create_free: 'prístup zadarmo', op_delete: 'vymazanie',
    op_resend_key: 'kľúč poslaný e-mailom', op_cancel_stripe: 'zrušenie predplatného', op_logout_all: 'odhlásenie všade', details: 'Podrobnosti',
  },
  en: {
    code: 'Authenticator code (6 digits)', needCode: 'Enter the 6-digit code from your authenticator app', badCode: 'Wrong code — check the time on your phone',
    logoutAll: 'Sign out everywhere', confirmLogoutAll: 'End every admin session, including this one?',
    secTitle: '🛡 Security', tfaOn: 'Password + authenticator code sign-in is on', tfaOff: 'Two-factor sign-in is off — the password is the only protection', tfaSetup: 'Turn on',
    tfaStep1: '1. Open Google Authenticator, Microsoft Authenticator or 1Password and scan the QR code (or enter the secret manually).',
    tfaStep2: '2. Enter the code from the app to check it:', tfaTest: 'Check code', tfaTestOk: '✅ The code is correct.',
    tfaStep3: (s) => `3. In Vercel → Settings → Environment Variables add ADMIN_TOTP_SECRET = ${s} and press Redeploy. From then on sign-in needs a code. Keep the secret somewhere safe.`,
    settingsMissing: 'The admin_log / admin_settings tables are missing — run the last block of schema.sql in Supabase. The journal and “Sign out everywhere” need them.',
    mTitle: '💶 Money', mMrr: 'Monthly revenue (MRR)', mArr: 'Yearly (ARR)', mPaying: 'Paying (Starter / Pro)', mConv: 'Trial → paid',
    mConvNote: (a, b) => `${a} of ${b} finished trials`, mChart: 'New subscriptions and cancellations, last 12 months', mNew: 'new', mCancel: 'cancelled',
    mNote: 'Live payments only. Prices: Starter €9.99, Pro €19.99. Cancellations by month of last change.',
    attTitle: '🔔 Needs attention', attPast: 'Payment problem', attTrial: 'Trial ends within 3 days', attSilent: 'Paying but silent for 14+ days', attNone: 'All quiet — nobody to chase.',
    open: 'Open', cTitle: 'Client card', cKeys: 'All keys with this email', cLogins: 'Owner dashboard sign-ins', cRegs: 'Online guest sign-ups', cMail: 'Emails in 30 days',
    cProfile: 'Business page', cNoLogins: 'No dashboard sign-ins yet', cFromTrial: 'started with a trial', cSub: 'Stripe subscription', cNoSub: 'no', cYes: 'yes',
    extend: '+ Extend trial', extendAsk: 'Extend the trial by how many days? (1–90)', resend: '✉ Email the key', resent: 'Key email sent',
    cancelSub: 'Cancel Stripe subscription', cancelEnd: 'At period end', cancelNow: 'Immediately',
    confirmCancelNow: 'Cancel the Stripe subscription immediately? The rest of the period is not refunded automatically.', confirmCancelEnd: 'Cancel at the end of the paid period? Until then the client uses the app as usual.',
    canceledOk: 'Subscription cancelled', close: 'Close', done: 'Done', stripeErr: (d) => 'Stripe error: ' + d, noSub: 'This key has no Stripe subscription', mailErr: 'Couldn’t send the email — check mail in “Launch readiness”',
    jTitle: '🧾 Action log', jEmpty: 'Nothing yet', jShow: 'Show', jHide: 'Hide', jMissing: 'The log appears once the admin_log table exists',
    op_login: 'admin sign-in', op_login_fail: 'failed sign-in', op_ban: 'ban', op_unban: 'unban', op_make_free: 'made free', op_make_paid: 'back to paid',
    op_note: 'note', op_set_tier: 'plan change', op_end_trial: 'trial ended', op_extend_trial: 'trial extended', op_create_free: 'free access granted', op_delete: 'deletion',
    op_resend_key: 'key emailed', op_cancel_stripe: 'subscription cancellation', op_logout_all: 'signed out everywhere', details: 'Details',
  },
};
