// GET /admin → /api/core?action=admin-page — админка владельца сервиса Loya.
const { dictJs } = require('./_dict');
const TX = {
  ru: {   rdyTitle: '🚀 Готовность к запуску', rdyAllOk: 'Всё готово к продажам', rdyNeed: (b, w) => [b ? `Нужно исправить: ${b}` : '', w ? `${b ? 'проверить' : 'Проверить'}: ${w}` : ''].filter(Boolean).join(', '), rdyShow: 'Показать', rdyHide: 'Скрыть',
  r_stripeMode: (v) => ({ live: 'Stripe: боевой режим — настоящие деньги', test: 'Stripe: тестовый режим — платежи ненастоящие. Для запуска продаж переключите на боевой', none: 'Stripe не подключён (нет STRIPE_SECRET_KEY)', unknown: 'Ключ Stripe не распознан' }[v] || v),
  r_price: (v) => ({ ok: `Цена найдена: ${(v.amount / 100).toFixed(2)} ${String(v.currency).toUpperCase()} / ${v.interval === 'month' ? 'мес.' : v.interval}`, mismatch: 'Ключ и цена из разных режимов (тест/бой) — страница оплаты не откроется. Создайте цену в нужном режиме и обновите STRIPE_PRICE_ID', notfound: 'Цена из STRIPE_PRICE_ID не найдена в этом режиме Stripe', missing: 'Не задана STRIPE_PRICE_ID', inactive: 'Цена в архиве — включите её в Stripe', notRecurring: 'Цена разовая — нужна подписка (ежемесячная)' }[v.s]),
  r_webhook: (v, l) => l === 'ok' ? 'Секрет вебхука Stripe задан' : 'Не задан STRIPE_WEBHOOK_SECRET — оплаты не будут создавать ключи',
  r_portal: (v, l) => l === 'ok' ? 'Ссылка на управление подпиской задана (/manage)' : 'Нет STRIPE_PORTAL_URL — клиенты не смогут сами отменить подписку. Создайте ссылку в Stripe: Settings → Billing → Customer portal',
  r_publicUrl: (v, l) => l === 'ok' ? 'Адрес сайта: loya-loyalty.com' : `PUBLIC_URL = ${v || 'не задан'} — должен быть https://loya-loyalty.com`,
  r_mail: (v) => ({ ok: 'Рабочая почта настроена', off: 'Рабочая почта не настроена (MAIL_USER / MAIL_PASS)', gmail: 'Почта через Gmail: лимит ~500 писем в сутки, письма чаще попадают в спам. Для продаж подключите почтовый сервис и свой домен', nofrom: 'Не задан MAIL_FROM — адрес отправителя должен быть на вашем домене' }[v]),
  r_wallet: (v) => v === 'mode' ? 'Google Wallet настроен. Режим публикации проверьте в консоли Google: пока на картах «[ТОЛЬКО ТЕСТИРОВАНИЕ]» — заявка на публикацию не одобрена' : 'Google Wallet не настроен',
  r_apple: (v, l) => l === 'ok' ? 'Apple Wallet подключён' : 'Apple Wallet не подключён (необязательно)',
  r_db: (v, l) => l === 'ok' ? 'База данных: все таблицы на месте' : `В базе не хватает: ${v}. Выполните schema.sql в Supabase`,
  r_testKeys: (n) => `Тестовых ключей: ${n}. Удалите их до запуска продаж: фильтр «Тестовые» → «Выбрать все» → «Удалить выбранные»`, fTest: 'Тестовые', chTest: 'ТЕСТ', chLive: 'боевой', csv: 'Скачать CSV', sTest: 'Тестовых ключей', modeLive: 'Stripe: БОЕВОЙ режим — настоящие деньги', modeTest: 'Stripe: ТЕСТОВЫЙ режим — платежи ненастоящие. Перед запуском продаж переключите на боевой и удалите тестовые ключи', modeNone: 'Stripe не подключён (нет STRIPE_SECRET_KEY)', modeUnknown: 'Stripe: ключ не распознан', del: 'Удалить', delSel: (n) => `Удалить выбранные (${n})`, selectAll: 'Выбрать все', delConfirm: (n) => `Удалить ${n} ключ(ей) навсегда? Вместе с ними удалятся их данные на сервере (доступ из дома, регистрация по ссылке, чеки, Apple Wallet). Отменить нельзя.`, delStripe: 'Внимание: у части ключей есть подписка Stripe. Удаление её НЕ отменяет — отмените подписку в кабинете Stripe, иначе клиенту продолжат списывать оплату.', deleted: (n) => `Удалено: ${n}`, title: 'Loya — админка', pass: 'Пароль администратора', login: 'Войти', wrong: 'Неверный пароль', locked: 'Слишком много попыток — подождите 15 минут', off: 'Админка выключена: задайте ADMIN_PASSWORD (от 12 символов) в переменных Vercel.', err: 'Ошибка. Попробуйте ещё раз.', logout: 'Выйти', refresh: 'Обновить',
    sTotal: 'Всего ключей', sActive: 'Активных', sPaying: 'Платят', sFree: 'Бесплатно', sBanned: 'Заблокировано', sOnline: 'Заходили за 7 дней', sPast: 'Проблема с оплатой', sCanceled: 'Отменено / истекло',
    fAll: 'Все', fActive: 'Активные', fFree: 'Бесплатные', fBanned: 'Заблокированные', fInactive: 'Неактивные', search: 'Поиск по email, ключу, заметке',
    newFree: '+ Бесплатный доступ', email: 'Email', note: 'Заметка (видна только вам)', until: 'Бесплатно до (необязательно)', create: 'Создать ключ', created: 'Готово! Ключ для клиента:', copy: 'Копировать', copied: 'Скопировано', cancel: 'Отмена',
    ban: 'Заблокировать', unban: 'Разблокировать', makeFree: 'Сделать бесплатным', makePaid: 'Вернуть платный', editNote: 'Заметка', confirmBan: 'Заблокировать этот ключ? Программа у клиента перестанет работать при следующей проверке.',
    st_active: 'активна', st_past_due: 'проблема с оплатой', st_canceled: 'отменена', st_banned: 'заблокирован', st_free_expired: 'бесплатный истёк', st_unknown: '?', planFree: 'бесплатно', planPaid: 'Stripe',
    lastSeen: 'Был на связи', never: 'ещё не выходил на связь', ver: 'версия', createdAt: 'создан', shown: (a, b) => `Показано ${a} из ${b}`, needEmail: 'Введите email', dbErr: (d) => 'Ошибка базы: ' + d + ' — выполните schema.sql в Supabase.' },
  uk: {   rdyTitle: '🚀 Готовність до запуску', rdyAllOk: 'Усе готово до продажів', rdyNeed: (b, w) => [b ? `Потрібно виправити: ${b}` : '', w ? `${b ? 'перевірити' : 'Перевірити'}: ${w}` : ''].filter(Boolean).join(', '), rdyShow: 'Показати', rdyHide: 'Сховати',
  r_stripeMode: (v) => ({ live: 'Stripe: бойовий режим — справжні гроші', test: 'Stripe: тестовий режим — платежі несправжні. Для запуску продажів перемкніть на бойовий', none: 'Stripe не підключено (немає STRIPE_SECRET_KEY)', unknown: 'Ключ Stripe не розпізнано' }[v] || v),
  r_price: (v) => ({ ok: `Ціну знайдено: ${(v.amount / 100).toFixed(2)} ${String(v.currency).toUpperCase()} / ${v.interval === 'month' ? 'міс.' : v.interval}`, mismatch: 'Ключ і ціна з різних режимів (тест/бій) — сторінка оплати не відкриється. Створіть ціну в потрібному режимі й оновіть STRIPE_PRICE_ID', notfound: 'Ціну з STRIPE_PRICE_ID не знайдено в цьому режимі Stripe', missing: 'Не задано STRIPE_PRICE_ID', inactive: 'Ціна в архіві — увімкніть її в Stripe', notRecurring: 'Ціна разова — потрібна підписка (щомісячна)' }[v.s]),
  r_webhook: (v, l) => l === 'ok' ? 'Секрет вебхука Stripe задано' : 'Не задано STRIPE_WEBHOOK_SECRET — оплати не створюватимуть ключі',
  r_portal: (v, l) => l === 'ok' ? 'Посилання на керування підпискою задано (/manage)' : 'Немає STRIPE_PORTAL_URL — клієнти не зможуть самі скасувати підписку. Створіть посилання в Stripe: Settings → Billing → Customer portal',
  r_publicUrl: (v, l) => l === 'ok' ? 'Адреса сайту: loya-loyalty.com' : `PUBLIC_URL = ${v || 'не задано'} — має бути https://loya-loyalty.com`,
  r_mail: (v) => ({ ok: 'Робоча пошта налаштована', off: 'Робоча пошта не налаштована (MAIL_USER / MAIL_PASS)', gmail: 'Пошта через Gmail: ліміт ~500 листів на добу, листи частіше потрапляють у спам. Для продажів підключіть поштовий сервіс і свій домен', nofrom: 'Не задано MAIL_FROM — адреса відправника має бути на вашому домені' }[v]),
  r_wallet: (v) => v === 'mode' ? 'Google Wallet налаштовано. Режим публікації перевірте в консолі Google: поки на картках «[ТІЛЬКИ ТЕСТУВАННЯ]» — заявку на публікацію не схвалено' : 'Google Wallet не налаштовано',
  r_apple: (v, l) => l === 'ok' ? 'Apple Wallet підключено' : 'Apple Wallet не підключено (необов’язково)',
  r_db: (v, l) => l === 'ok' ? 'База даних: усі таблиці на місці' : `У базі бракує: ${v}. Виконайте schema.sql у Supabase`,
  r_testKeys: (n) => `Тестових ключів: ${n}. Видаліть їх до запуску продажів: фільтр «Тестові» → «Вибрати всі» → «Видалити вибрані»`, fTest: 'Тестові', chTest: 'ТЕСТ', chLive: 'бойовий', csv: 'Завантажити CSV', sTest: 'Тестових ключів', modeLive: 'Stripe: БОЙОВИЙ режим — справжні гроші', modeTest: 'Stripe: ТЕСТОВИЙ режим — платежі несправжні. Перед запуском продажів перемкніть на бойовий і видаліть тестові ключі', modeNone: 'Stripe не підключено (немає STRIPE_SECRET_KEY)', modeUnknown: 'Stripe: ключ не розпізнано', del: 'Видалити', delSel: (n) => `Видалити вибрані (${n})`, selectAll: 'Вибрати всі', delConfirm: (n) => `Видалити ${n} ключ(ів) назавжди? Разом із ними видаляться їхні дані на сервері (доступ з дому, реєстрація за посиланням, чеки, Apple Wallet). Скасувати не можна.`, delStripe: 'Увага: у частини ключів є підписка Stripe. Видалення її НЕ скасовує — скасуйте підписку в кабінеті Stripe, інакше клієнту продовжать списувати оплату.', deleted: (n) => `Видалено: ${n}`, title: 'Loya — адмінка', pass: 'Пароль адміністратора', login: 'Увійти', wrong: 'Невірний пароль', locked: 'Забагато спроб — зачекайте 15 хвилин', off: 'Адмінку вимкнено: задайте ADMIN_PASSWORD (від 12 символів) у змінних Vercel.', err: 'Помилка. Спробуйте ще раз.', logout: 'Вийти', refresh: 'Оновити',
    sTotal: 'Усього ключів', sActive: 'Активних', sPaying: 'Платять', sFree: 'Безкоштовно', sBanned: 'Заблоковано', sOnline: 'Заходили за 7 днів', sPast: 'Проблема з оплатою', sCanceled: 'Скасовано / минуло',
    fAll: 'Усі', fActive: 'Активні', fFree: 'Безкоштовні', fBanned: 'Заблоковані', fInactive: 'Неактивні', search: 'Пошук за email, ключем, нотаткою',
    newFree: '+ Безкоштовний доступ', email: 'Email', note: 'Нотатка (бачите лише ви)', until: 'Безкоштовно до (необов’язково)', create: 'Створити ключ', created: 'Готово! Ключ для клієнта:', copy: 'Копіювати', copied: 'Скопійовано', cancel: 'Скасувати',
    ban: 'Заблокувати', unban: 'Розблокувати', makeFree: 'Зробити безкоштовним', makePaid: 'Повернути платний', editNote: 'Нотатка', confirmBan: 'Заблокувати цей ключ? Програма в клієнта перестане працювати під час наступної перевірки.',
    st_active: 'активна', st_past_due: 'проблема з оплатою', st_canceled: 'скасована', st_banned: 'заблоковано', st_free_expired: 'безкоштовний минув', st_unknown: '?', planFree: 'безкоштовно', planPaid: 'Stripe',
    lastSeen: 'Був на зв’язку', never: 'ще не виходив на зв’язок', ver: 'версія', createdAt: 'створено', shown: (a, b) => `Показано ${a} з ${b}`, needEmail: 'Введіть email', dbErr: (d) => 'Помилка бази: ' + d + ' — виконайте schema.sql у Supabase.' },
  sk: {   rdyTitle: '🚀 Pripravenosť na spustenie', rdyAllOk: 'Všetko pripravené na predaj', rdyNeed: (b, w) => [b ? `Treba opraviť: ${b}` : '', w ? `${b ? 'skontrolovať' : 'Skontrolovať'}: ${w}` : ''].filter(Boolean).join(', '), rdyShow: 'Zobraziť', rdyHide: 'Skryť',
  r_stripeMode: (v) => ({ live: 'Stripe: ostrý režim — skutočné peniaze', test: 'Stripe: testovací režim — platby nie sú skutočné. Pred spustením predaja prepnite na ostrý', none: 'Stripe nie je pripojený (chýba STRIPE_SECRET_KEY)', unknown: 'Kľúč Stripe sa nepodarilo rozpoznať' }[v] || v),
  r_price: (v) => ({ ok: `Cena nájdená: ${(v.amount / 100).toFixed(2)} ${String(v.currency).toUpperCase()} / ${v.interval === 'month' ? 'mes.' : v.interval}`, mismatch: 'Kľúč a cena sú z rôznych režimov (test/ostrý) — platobná stránka sa neotvorí. Vytvorte cenu v správnom režime a aktualizujte STRIPE_PRICE_ID', notfound: 'Cena zo STRIPE_PRICE_ID sa v tomto režime Stripe nenašla', missing: 'Nie je nastavená STRIPE_PRICE_ID', inactive: 'Cena je archivovaná — zapnite ju v Stripe', notRecurring: 'Cena je jednorazová — treba predplatné (mesačné)' }[v.s]),
  r_webhook: (v, l) => l === 'ok' ? 'Tajomstvo webhooku Stripe je nastavené' : 'Chýba STRIPE_WEBHOOK_SECRET — platby nebudú vytvárať kľúče',
  r_portal: (v, l) => l === 'ok' ? 'Odkaz na správu predplatného je nastavený (/manage)' : 'Chýba STRIPE_PORTAL_URL — klienti si nebudú môcť predplatné sami zrušiť. Vytvorte odkaz v Stripe: Settings → Billing → Customer portal',
  r_publicUrl: (v, l) => l === 'ok' ? 'Adresa webu: loya-loyalty.com' : `PUBLIC_URL = ${v || 'nenastavená'} — má byť https://loya-loyalty.com`,
  r_mail: (v) => ({ ok: 'Pracovný e-mail je nastavený', off: 'Pracovný e-mail nie je nastavený (MAIL_USER / MAIL_PASS)', gmail: 'E-mail cez Gmail: limit ~500 správ denne, správy častejšie končia v spame. Na predaj pripojte e-mailovú službu a vlastnú doménu', nofrom: 'Chýba MAIL_FROM — adresa odosielateľa má byť na vašej doméne' }[v]),
  r_wallet: (v) => v === 'mode' ? 'Google Wallet je nastavený. Režim zverejnenia skontrolujte v konzole Google: kým sú na kartách „[IBA TESTOVANIE]“, žiadosť o zverejnenie nie je schválená' : 'Google Wallet nie je nastavený',
  r_apple: (v, l) => l === 'ok' ? 'Apple Wallet je pripojený' : 'Apple Wallet nie je pripojený (nepovinné)',
  r_db: (v, l) => l === 'ok' ? 'Databáza: všetky tabuľky sú na mieste' : `V databáze chýba: ${v}. Spustite schema.sql v Supabase`,
  r_testKeys: (n) => `Testovacích kľúčov: ${n}. Vymažte ich pred spustením predaja: filter „Testovacie“ → „Vybrať všetky“ → „Vymazať vybrané“`, fTest: 'Testovacie', chTest: 'TEST', chLive: 'ostrý', csv: 'Stiahnuť CSV', sTest: 'Testovacích kľúčov', modeLive: 'Stripe: OSTRÝ režim — skutočné peniaze', modeTest: 'Stripe: TESTOVACÍ režim — platby nie sú skutočné. Pred spustením predaja prepnite na ostrý a vymažte testovacie kľúče', modeNone: 'Stripe nie je pripojený (chýba STRIPE_SECRET_KEY)', modeUnknown: 'Stripe: kľúč sa nepodarilo rozpoznať', del: 'Vymazať', delSel: (n) => `Vymazať vybrané (${n})`, selectAll: 'Vybrať všetky', delConfirm: (n) => `Natrvalo vymazať ${n} kľúč(ov)? Spolu s nimi sa vymažú ich údaje na serveri (prístup z domu, registrácia cez odkaz, doklady, Apple Wallet). Nedá sa to vrátiť.`, delStripe: 'Pozor: niektoré kľúče majú predplatné Stripe. Vymazanie ho NEZRUŠÍ — zrušte predplatné v Stripe, inak sa klientovi bude ďalej strhávať platba.', deleted: (n) => `Vymazané: ${n}`, title: 'Loya — administrácia', pass: 'Heslo administrátora', login: 'Prihlásiť', wrong: 'Nesprávne heslo', locked: 'Príliš veľa pokusov — počkajte 15 minút', off: 'Administrácia je vypnutá: nastavte ADMIN_PASSWORD (aspoň 12 znakov) v premenných Vercel.', err: 'Chyba. Skúste znova.', logout: 'Odhlásiť', refresh: 'Obnoviť',
    sTotal: 'Spolu kľúčov', sActive: 'Aktívnych', sPaying: 'Platia', sFree: 'Zadarmo', sBanned: 'Zablokovaných', sOnline: 'Online za 7 dní', sPast: 'Problém s platbou', sCanceled: 'Zrušené / vypršané',
    fAll: 'Všetky', fActive: 'Aktívne', fFree: 'Zadarmo', fBanned: 'Zablokované', fInactive: 'Neaktívne', search: 'Hľadať podľa e-mailu, kľúča, poznámky',
    newFree: '+ Prístup zadarmo', email: 'E-mail', note: 'Poznámka (vidíte len vy)', until: 'Zadarmo do (nepovinné)', create: 'Vytvoriť kľúč', created: 'Hotovo! Kľúč pre klienta:', copy: 'Kopírovať', copied: 'Skopírované', cancel: 'Zrušiť',
    ban: 'Zablokovať', unban: 'Odblokovať', makeFree: 'Nastaviť zadarmo', makePaid: 'Vrátiť platený', editNote: 'Poznámka', confirmBan: 'Zablokovať tento kľúč? Program u klienta prestane fungovať pri ďalšej kontrole.',
    st_active: 'aktívne', st_past_due: 'problém s platbou', st_canceled: 'zrušené', st_banned: 'zablokovaný', st_free_expired: 'zadarmo vypršalo', st_unknown: '?', planFree: 'zadarmo', planPaid: 'Stripe',
    lastSeen: 'Naposledy online', never: 'ešte sa neozval', ver: 'verzia', createdAt: 'vytvorený', shown: (a, b) => `Zobrazených ${a} z ${b}`, needEmail: 'Zadajte e-mail', dbErr: (d) => 'Chyba databázy: ' + d + ' — spustite schema.sql v Supabase.' },
  en: {   rdyTitle: '🚀 Launch readiness', rdyAllOk: 'Everything is ready for sales', rdyNeed: (b, w) => [b ? `To fix: ${b}` : '', w ? `${b ? 'to check' : 'To check'}: ${w}` : ''].filter(Boolean).join(', '), rdyShow: 'Show', rdyHide: 'Hide',
  r_stripeMode: (v) => ({ live: 'Stripe: live mode — real money', test: 'Stripe: test mode — payments aren’t real. Switch to live before launch', none: 'Stripe isn’t connected (no STRIPE_SECRET_KEY)', unknown: 'Stripe key not recognised' }[v] || v),
  r_price: (v) => ({ ok: `Price found: ${(v.amount / 100).toFixed(2)} ${String(v.currency).toUpperCase()} / ${v.interval}`, mismatch: 'The key and the price are from different modes (test/live) — checkout won’t open. Create the price in the right mode and update STRIPE_PRICE_ID', notfound: 'The price from STRIPE_PRICE_ID wasn’t found in this Stripe mode', missing: 'STRIPE_PRICE_ID isn’t set', inactive: 'The price is archived — activate it in Stripe', notRecurring: 'The price is one-time — a monthly subscription is needed' }[v.s]),
  r_webhook: (v, l) => l === 'ok' ? 'Stripe webhook secret is set' : 'STRIPE_WEBHOOK_SECRET isn’t set — payments won’t create keys',
  r_portal: (v, l) => l === 'ok' ? 'Subscription management link is set (/manage)' : 'No STRIPE_PORTAL_URL — customers can’t cancel on their own. Create the link in Stripe: Settings → Billing → Customer portal',
  r_publicUrl: (v, l) => l === 'ok' ? 'Site address: loya-loyalty.com' : `PUBLIC_URL = ${v || 'not set'} — it should be https://loya-loyalty.com`,
  r_mail: (v) => ({ ok: 'Business mail is set up', off: 'Business mail isn’t set up (MAIL_USER / MAIL_PASS)', gmail: 'Mail via Gmail: ~500 messages/day limit and more spam-foldering. Connect a mail service and your own domain for sales', nofrom: 'MAIL_FROM isn’t set — the sender address should be on your domain' }[v]),
  r_wallet: (v) => v === 'mode' ? 'Google Wallet is set up. Check the publishing status in the Google console: while cards show “[TEST ONLY]”, the publishing request isn’t approved' : 'Google Wallet isn’t set up',
  r_apple: (v, l) => l === 'ok' ? 'Apple Wallet is connected' : 'Apple Wallet isn’t connected (optional)',
  r_db: (v, l) => l === 'ok' ? 'Database: all tables in place' : `The database is missing: ${v}. Run schema.sql in Supabase`,
  r_testKeys: (n) => `Test keys: ${n}. Delete them before launch: filter “Test” → “Select all” → “Delete selected”`, fTest: 'Test', chTest: 'TEST', chLive: 'live', csv: 'Download CSV', sTest: 'Test keys', modeLive: 'Stripe: LIVE mode — real money', modeTest: 'Stripe: TEST mode — payments aren’t real. Before launch, switch to live and delete the test keys', modeNone: 'Stripe isn’t connected (no STRIPE_SECRET_KEY)', modeUnknown: 'Stripe: key not recognised', del: 'Delete', delSel: (n) => `Delete selected (${n})`, selectAll: 'Select all', delConfirm: (n) => `Delete ${n} key(s) for good? Their server data goes too (access from home, sign-up by link, receipts, Apple Wallet). This can’t be undone.`, delStripe: 'Note: some of these keys have a Stripe subscription. Deleting does NOT cancel it — cancel it in the Stripe dashboard, or the client keeps being charged.', deleted: (n) => `Deleted: ${n}`, title: 'Loya — admin', pass: 'Admin password', login: 'Sign in', wrong: 'Wrong password', locked: 'Too many attempts — wait 15 minutes', off: 'Admin is off: set ADMIN_PASSWORD (12+ characters) in Vercel variables.', err: 'Error. Please try again.', logout: 'Sign out', refresh: 'Refresh',
    sTotal: 'Total keys', sActive: 'Active', sPaying: 'Paying', sFree: 'Free', sBanned: 'Banned', sOnline: 'Online in 7 days', sPast: 'Payment issue', sCanceled: 'Canceled / expired',
    fAll: 'All', fActive: 'Active', fFree: 'Free', fBanned: 'Banned', fInactive: 'Inactive', search: 'Search by email, key, note',
    newFree: '+ Free access', email: 'Email', note: 'Note (only you see it)', until: 'Free until (optional)', create: 'Create key', created: 'Done! Key for the client:', copy: 'Copy', copied: 'Copied', cancel: 'Cancel',
    ban: 'Ban', unban: 'Unban', makeFree: 'Make free', makePaid: 'Back to paid', editNote: 'Note', confirmBan: 'Ban this key? The client’s app stops working at its next check.',
    st_active: 'active', st_past_due: 'payment issue', st_canceled: 'canceled', st_banned: 'banned', st_free_expired: 'free expired', st_unknown: '?', planFree: 'free', planPaid: 'Stripe',
    lastSeen: 'Last online', never: 'never checked in', ver: 'version', createdAt: 'created', shown: (a, b) => `Showing ${a} of ${b}`, needEmail: 'Enter an email', dbErr: (d) => 'Database error: ' + d + ' — run schema.sql in Supabase.' }
};
const PAGE = () => `<!DOCTYPE html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="robots" content="noindex,nofollow"><meta name="referrer" content="no-referrer"><title>Loya admin</title>
<style>
:root{--a:#d4af37;--bg:#0d0f14;--card:#151922;--line:rgba(255,255,255,.09);--mut:rgba(243,239,230,.6)}*{box-sizing:border-box;margin:0}
body{font-family:'Segoe UI',system-ui,-apple-system,Arial,sans-serif;background:var(--bg);color:#f3efe6;padding:16px 16px 40px}
.wrap{max-width:1100px;margin:0 auto}.top{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin-bottom:14px}.top h1{flex:1;font-size:20px;min-width:160px}
.pill{border:1px solid var(--line);background:rgba(255,255,255,.05);color:inherit;border-radius:10px;padding:7px 11px;font:inherit;font-size:13px;font-weight:700;cursor:pointer}.pill.on{background:var(--a);border-color:var(--a);color:#16110a}
.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(118px,1fr));gap:10px;margin-bottom:14px}.stat{background:var(--card);border:1px solid rgba(255,255,255,.14);border-radius:14px;padding:12px}.stat b{display:block;font-size:24px}.stat span{font-size:12px;color:var(--mut)}
.bar{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:12px;align-items:center}
input{height:44px;border-radius:10px;border:1px solid rgba(255,255,255,.16);background:rgba(255,255,255,.05);color:inherit;padding:0 12px;font:inherit;font-size:15px}input:focus{outline:none;border-color:var(--a)}
.btn{height:44px;border:0;border-radius:10px;font:inherit;font-weight:800;color:#16110a;background:var(--a);cursor:pointer;padding:0 16px}.btn.sec{background:rgba(255,255,255,.08);color:inherit}
.row{display:flex;gap:12px;align-items:flex-start;justify-content:space-between;padding:12px 14px;border-top:1px solid var(--line);flex-wrap:wrap}.row:first-child{border-top:0}
.list{background:var(--card);border:1px solid var(--line);border-radius:16px}.who b{font-size:14.5px}.who small{display:block;color:var(--mut);font-size:12px;margin-top:2px}
.key{font-family:Consolas,monospace;font-size:12.5px;color:var(--a)}.acts{display:flex;gap:6px;flex-wrap:wrap;align-items:center}
.act{min-height:34px;padding:0 12px;border-radius:10px;font:inherit;font-size:12.5px;font-weight:800;cursor:pointer;border:1.5px solid;background:transparent;transition:background .15s,color .15s}
.a-ban{color:#fca5a5;border-color:rgba(248,113,113,.7);background:rgba(239,68,68,.1)}.a-ban:hover{background:rgba(239,68,68,.25)}
.a-unban{color:#86efac;border-color:rgba(74,222,128,.7);background:rgba(34,197,94,.1)}.a-unban:hover{background:rgba(34,197,94,.25)}
.a-free{color:#93c5fd;border-color:rgba(96,165,250,.7);background:rgba(59,130,246,.1)}.a-free:hover{background:rgba(59,130,246,.25)}
.a-paid{color:#e9d5ff;border-color:rgba(192,132,252,.7);background:rgba(168,85,247,.1)}.a-paid:hover{background:rgba(168,85,247,.25)}
.a-note{color:#fde68a;border-color:rgba(251,191,36,.7);background:rgba(245,158,11,.1)}.a-note:hover{background:rgba(245,158,11,.25)}
.a-copy{color:#f3efe6;border-color:rgba(255,255,255,.4);background:rgba(255,255,255,.06)}.a-copy:hover{background:rgba(255,255,255,.14)}
.a-del{color:#fff;border-color:#dc2626;background:#b91c1c}.a-del:hover{background:#dc2626}
.sel{width:20px;height:20px;accent-color:var(--a);margin:2px 12px 0 0;flex-shrink:0;cursor:pointer}
.who{display:flex;align-items:flex-start}
.bulk{display:flex;align-items:center;gap:12px;flex-wrap:wrap;margin:0 0 10px;padding:10px 14px;border-radius:14px;background:rgba(239,68,68,.1);border:1px solid rgba(248,113,113,.5)}
.selall{display:inline-flex;align-items:center;gap:8px;font-size:13px;font-weight:700;color:var(--mut);cursor:pointer}
.stat{border-left:4px solid var(--c,#d4af37)}.stat b{color:var(--c,#f3efe6)}
.pill{border-color:rgba(255,255,255,.3)!important}
.chip{display:inline-block;font-size:11px;font-weight:800;border-radius:7px;padding:2px 7px;margin-left:6px;vertical-align:middle;border:1px solid currentColor}.c-ok{background:rgba(34,197,94,.16);color:#86efac}.c-bad{background:rgba(239,68,68,.16);color:#fca5a5}.c-warn{background:rgba(245,158,11,.16);color:#fcd34d}.c-free{background:rgba(96,165,250,.16);color:#93c5fd}
.login{max-width:340px;margin:14vh auto 0;display:flex;flex-direction:column;gap:10px;text-align:center}.err{color:#fca5a5;font-size:14px;min-height:18px}.ok{color:#86efac}
.modal{position:fixed;inset:0;background:rgba(0,0,0,.65);display:flex;align-items:center;justify-content:center;padding:16px}.modal .in{background:#151922;border:1px solid var(--line);border-radius:18px;padding:18px;width:100%;max-width:420px;display:flex;flex-direction:column;gap:10px}
.hide{display:none!important}
.rdy{border:1.5px solid rgba(255,255,255,.2);border-radius:14px;margin-bottom:12px;background:var(--card);overflow:hidden}
.rdy-h{display:flex;align-items:center;gap:10px;padding:11px 14px;cursor:pointer;font-weight:800;font-size:14px}.rdy-h .sp{flex:1}
.rdy-b{padding:4px 14px 12px;display:flex;flex-direction:column;gap:6px}
.rdy-i{display:flex;gap:10px;align-items:flex-start;font-size:13.5px;line-height:1.45;padding:7px 10px;border-radius:10px;border:1px solid}
.rdy-i.ok{border-color:rgba(74,222,128,.5);background:rgba(34,197,94,.08)}.rdy-i.warn{border-color:rgba(251,191,36,.7);background:rgba(245,158,11,.1)}.rdy-i.bad{border-color:rgba(248,113,113,.75);background:rgba(239,68,68,.12)}.rdy-i.info{border-color:rgba(147,197,253,.5);background:rgba(59,130,246,.08)}
.rdy-tag{font-size:12px;font-weight:800;padding:3px 9px;border-radius:8px}.rdy-tag.ok{background:rgba(34,197,94,.18);color:#86efac}.rdy-tag.bad{background:rgba(239,68,68,.2);color:#fca5a5}.rdy-tag.warn{background:rgba(245,158,11,.2);color:#fde68a}
.mode{display:flex;align-items:center;gap:10px;padding:10px 14px;border-radius:12px;margin-bottom:12px;font-size:13.5px;font-weight:800;border:1.5px solid}
.mode.m-live{color:#86efac;border-color:rgba(74,222,128,.7);background:rgba(34,197,94,.1)}.mode.m-test{color:#fde68a;border-color:rgba(251,191,36,.8);background:rgba(245,158,11,.13)}.mode.m-none{color:#fca5a5;border-color:rgba(248,113,113,.7);background:rgba(239,68,68,.1)}
.c-test{background:rgba(251,191,36,.18);color:#fde68a}
</style></head><body><div class="wrap">
<div id="lg" class="login hide"><h1>🔐 Loya</h1><input type="password" id="pw" autocomplete="current-password"><div class="err" id="lerr"></div><button class="btn" id="lb"></button><div class="top" style="justify-content:center" id="lang0"></div></div>
<div id="app" class="hide"><div class="top"><h1 id="ttl"></h1><span id="lang1" style="display:flex;gap:6px"></span><button class="pill" id="rf"></button><button class="pill" id="lo"></button></div>
<div class="mode" id="mode"></div><div class="rdy hide" id="rdy"></div><div class="grid" id="stats"></div>
<div class="bar"><span id="filters" style="display:flex;gap:6px;flex-wrap:wrap"></span><input id="q" style="flex:1;min-width:200px"><button class="btn" id="nf"></button></div>
<div class="err" id="aerr"></div><div class="bulk hide" id="bulk"><label class="selall"><input type="checkbox" id="selall" class="sel" style="margin:0"><span id="selall-t"></span></label><button class="act a-del" id="bulkdel"></button><button class="act a-copy" id="csvbtn" type="button"></button><span id="bulkmsg" style="font-size:13px"></span></div><div class="list" id="list"></div><p id="shown" style="text-align:center;color:var(--mut);font-size:12.5px;margin-top:8px"></p></div>
</div><div id="modal" class="modal hide"><div class="in" id="mb"></div></div>
<script>
const TXT=${dictJs(TX)};
let lang=(function(){try{const s=localStorage.getItem('loya_admin_lang');if(TXT[s])return s}catch(e){}const k=String(navigator.language||'').slice(0,2);return TXT[k]?k:(k==='cs'?'sk':'ru')})();
let session=null,D=null,filter='all',q='';const selected=new Set();let rdyOpen=null;try{session=sessionStorage.getItem('loya_admin_s')}catch(e){}
const $=id=>document.getElementById(id),E=s=>String(s==null?'':s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),T=()=>TXT[lang];
async function api(p,b){const r=await fetch('/api/'+p,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.assign({session},b||{}))});let j={};try{j=await r.json()}catch(e){}j._s=r.status;return j}
function langs(id){$(id).innerHTML=Object.keys(TXT).map(k=>'<button class="pill '+(k===lang?'on':'')+'" data-l="'+k+'">'+k.toUpperCase()+'</button>').join('');$(id).querySelectorAll('button').forEach(b=>b.onclick=()=>{lang=b.dataset.l;try{localStorage.setItem('loya_admin_lang',lang)}catch(e){}paint()})}
const dt=s=>s?new Date(s).toLocaleString(lang==='en'?'en-GB':lang,{dateStyle:'short',timeStyle:'short'}):'';
function paint(){const t=T();document.title=t.title;$('pw').placeholder=t.pass;$('lb').textContent=t.login;langs('lang0');
if(!session||!D){$('lg').classList.remove('hide');$('app').classList.add('hide');return}
$('lg').classList.add('hide');$('app').classList.remove('hide');langs('lang1');$('ttl').textContent=t.title;$('rf').textContent='↻ '+t.refresh;$('lo').textContent=t.logout;$('nf').textContent=t.newFree;$('q').placeholder=t.search;
const s=D.stats;$('stats').innerHTML=[[s.total,t.sTotal,'#e5e7eb'],[s.active,t.sActive,'#4ade80'],[s.paying,t.sPaying,'#fbbf24'],[s.free,t.sFree,'#60a5fa'],[s.online7,t.sOnline,'#2dd4bf'],[s.test||0,t.sTest,'#fbbf24'],[s.banned,t.sBanned,'#f87171'],[s.pastDue,t.sPast,'#fb923c'],[s.canceled,t.sCanceled,'#a1a1aa']].map(x=>'<div class="stat" style="--c:'+x[2]+'"><b>'+x[0]+'</b><span>'+E(x[1])+'</span></div>').join('');
$('filters').innerHTML=[['all',t.fAll],['active',t.fActive],['free',t.fFree],['banned',t.fBanned],['inactive',t.fInactive],['test',t.fTest]].map(f=>'<button class="pill '+(filter===f[0]?'on':'')+'" data-f="'+f[0]+'">'+E(f[1])+'</button>').join('');
$('filters').querySelectorAll('button').forEach(b=>b.onclick=()=>{filter=b.dataset.f;paint()});
const qq=q.trim().toLowerCase();let L=D.list.filter(x=>filter==='all'||(filter==='active'&&x.state==='active')||(filter==='free'&&x.plan==='free')||(filter==='banned'&&x.banned)||(filter==='inactive'&&x.state!=='active')||(filter==='test'&&x.livemode===false));
if(qq)L=L.filter(x=>(x.email+' '+x.key+' '+x.note).toLowerCase().includes(qq));const total=L.length;L=L.slice(0,300);
const modeChip=x=>x.livemode===false?'<span class="chip c-test">'+E(t.chTest)+'</span>':x.livemode===true?'<span class="chip c-free">'+E(t.chLive)+'</span>':'';
const chip=x=>x.banned?'<span class="chip c-bad">'+E(t.st_banned)+'</span>':x.state==='active'?'<span class="chip c-ok">'+E(t.st_active)+'</span>':x.state==='past_due'?'<span class="chip c-warn">'+E(t.st_past_due)+'</span>':'<span class="chip c-bad">'+E(t['st_'+x.state]||x.state)+'</span>';
$('list').innerHTML=L.map(x=>'<div class="row"><div class="who"><input type="checkbox" class="sel" data-sel="'+E(x.key)+'"'+(selected.has(x.key)?' checked':'')+'><div><b>'+E(x.email||'—')+'</b>'+chip(x)+modeChip(x)+(x.plan==='free'?'<span class="chip c-free">'+E(t.planFree)+(x.freeUntil?' → '+E(x.freeUntil):'')+'</span>':'')+
'<small><span class="key">'+E(x.key)+'</span> · '+E(t.createdAt)+' '+E(dt(x.created))+'</small><small>'+E(t.lastSeen)+': '+E(x.lastSeen?dt(x.lastSeen):t.never)+(x.version?' · '+E(t.ver)+' '+E(x.version):'')+'</small>'+(x.note?'<small>📝 '+E(x.note)+'</small>':'')+'</div></div>'+
'<div class="acts">'+(x.banned?'<button class="act a-unban" data-op="unban" data-k="'+E(x.key)+'">'+E(t.unban)+'</button>':'<button class="act a-ban" data-op="ban" data-k="'+E(x.key)+'">'+E(t.ban)+'</button>')+
(x.plan==='free'?'<button class="act a-paid" data-op="make_paid" data-k="'+E(x.key)+'">'+E(t.makePaid)+'</button>':'<button class="act a-free" data-op="make_free" data-k="'+E(x.key)+'">'+E(t.makeFree)+'</button>')+
'<button class="act a-note" data-op="note" data-k="'+E(x.key)+'">'+E(t.editNote)+'</button><button class="act a-copy" data-copy="'+E(x.key)+'">'+E(t.copy)+'</button><button class="act a-del" data-del="'+E(x.key)+'">🗑 '+E(t.del)+'</button></div></div>').join('')||'<div class="row" style="color:var(--mut)">—</div>';
$('shown').textContent=t.shown(L.length,total);
const rd=D.ready;if(rd){const ic={ok:'✅',warn:'⚠️',bad:'❌',info:'ℹ️'};const rows=rd.items.map(i=>{const f=t['r_'+i.id];return f?'<div class="rdy-i '+i.level+'"><span>'+ic[i.level]+'</span><span>'+E(f(i.v,i.level))+'</span></div>':''}).join('');
const tag=rd.bad||rd.warn?'<span class="rdy-tag '+(rd.bad?'bad':'warn')+'">'+E(t.rdyNeed(rd.bad,rd.warn))+'</span>':'<span class="rdy-tag ok">'+E(t.rdyAllOk)+'</span>';
const open=rdyOpen===null?(rd.bad>0||rd.warn>0):rdyOpen;$('rdy').classList.remove('hide');$('rdy').innerHTML='<div class="rdy-h" id="rdy-h"><span>'+E(t.rdyTitle)+(rd.version?' · v'+E(rd.version):'')+'</span><span class="sp"></span>'+tag+'<span>'+(open?'▲':'▼')+'</span></div>'+(open?'<div class="rdy-b">'+rows+'</div>':'');$('rdy-h').onclick=()=>{rdyOpen=!open;paint()}}
const mm=D.stripeMode||'none';$('mode').className='mode m-'+(mm==='live'?'live':mm==='test'?'test':'none');$('mode').textContent=(mm==='live'?'✅ ':'⚠️ ')+(mm==='live'?t.modeLive:mm==='test'?t.modeTest:mm==='unknown'?t.modeUnknown:t.modeNone);
$('list').querySelectorAll('[data-op]').forEach(b=>b.onclick=()=>act(b.dataset.op,b.dataset.k));
$('list').querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>delKeys([b.dataset.del]));
$('list').querySelectorAll('[data-sel]').forEach(c=>c.onchange=()=>{c.checked?selected.add(c.dataset.sel):selected.delete(c.dataset.sel);bulkBar(L)});
$('selall').onchange=()=>{L.forEach(x=>$('selall').checked?selected.add(x.key):selected.delete(x.key));paint()};
bulkBar(L);
$('list').querySelectorAll('[data-copy]').forEach(b=>b.onclick=async()=>{try{await navigator.clipboard.writeText(b.dataset.copy);b.textContent=T().copied}catch(e){}})}
async function load(){const r=await api('admin-data');if(r._s===401){session=null;D=null;try{sessionStorage.removeItem('loya_admin_s')}catch(e){}paint();return}
if(!r.ok){$('aerr').textContent=r.error==='db_error'?T().dbErr(r.detail||''):T().err;return}$('aerr').textContent='';D=r;paint()}
function bulkBar(L){const t=T();[...selected].forEach(k=>{if(!D.list.some(x=>x.key===k))selected.delete(k)});const n=selected.size;$('bulk').classList.toggle('hide',!D.list.length);
$('selall-t').textContent=t.selectAll;$('selall').checked=L.length>0&&L.every(x=>selected.has(x.key));$('bulkdel').textContent='🗑 '+t.delSel(n);$('bulkdel').disabled=!n;$('bulkdel').style.opacity=n?1:.5;
$('bulkdel').onclick=()=>{if(n)delKeys([...selected])};
$('csvbtn').textContent='⬇ '+t.csv;$('csvbtn').onclick=()=>{const cell=v=>{let s=String(v==null?'':v);if(/^[=+\\-@]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"'};
const rows=[['email','key','state','plan','free_until','created','last_seen','version','livemode','note']].concat(D.list.map(x=>[x.email,x.key,x.state,x.plan,x.freeUntil,x.created,x.lastSeen,x.version,x.livemode===null?'':x.livemode,x.note]));
const blob=new Blob(['\\ufeff'+rows.map(r=>r.map(cell).join(',')).join('\\r\\n')],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='loya-keys-'+new Date().toISOString().slice(0,10)+'.csv';document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},500)}}
async function delKeys(keys){const t=T();const stripe=D.list.some(x=>keys.includes(x.key)&&x.hasStripe);
if(!confirm(t.delConfirm(keys.length)+(stripe?'\\n\\n'+t.delStripe:'')))return;
const r=await api('admin-action',{op:'delete',keys});if(!r.ok){$('aerr').textContent=r.error==='db_error'?t.dbErr(r.detail||''):t.err;return}
keys.forEach(k=>selected.delete(k));await load();$('bulkmsg').textContent=t.deleted(r.deleted)}
async function act(op,key){const t=T();let note,freeUntil;
if(op==='ban'&&!confirm(t.confirmBan))return;
if(op==='note'){const cur=(D.list.find(x=>x.key===key)||{}).note||'';note=prompt(t.note,cur);if(note===null)return}
if(op==='make_free'){freeUntil=prompt(t.until+' (YYYY-MM-DD)','');if(freeUntil===null)return}
const r=await api('admin-action',{op,key,note,freeUntil});if(!r.ok){$('aerr').textContent=r.error==='db_error'?t.dbErr(r.detail||''):t.err;return}load()}
$('nf').onclick=()=>{const t=T();$('mb').innerHTML='<b>'+E(t.newFree)+'</b><input id="m-e" type="email" placeholder="'+E(t.email)+'"><input id="m-n" placeholder="'+E(t.note)+'"><label style="font-size:13px;color:var(--mut)">'+E(t.until)+'<input id="m-u" type="date" style="width:100%;margin-top:4px;color-scheme:dark"></label><div class="err" id="m-err"></div><div style="display:flex;gap:8px"><button class="btn" id="m-ok" style="flex:1">'+E(t.create)+'</button><button class="btn sec" id="m-no">'+E(t.cancel)+'</button></div>';
$('modal').classList.remove('hide');$('m-no').onclick=()=>$('modal').classList.add('hide');
$('m-ok').onclick=async()=>{const email=$('m-e').value.trim();if(!email){$('m-err').textContent=t.needEmail;return}$('m-ok').disabled=true;
const r=await api('admin-action',{op:'create_free',email,note:$('m-n').value,freeUntil:$('m-u').value});
if(!r.ok){$('m-ok').disabled=false;$('m-err').textContent=r.error==='db_error'?t.dbErr(r.detail||''):t.err;return}
$('mb').innerHTML='<div class="ok">'+E(t.created)+'</div><div class="key" style="font-size:20px;text-align:center;padding:8px">'+E(r.key)+'</div><div style="display:flex;gap:8px"><button class="btn" id="m-c" style="flex:1">'+E(t.copy)+'</button><button class="btn sec" id="m-x">OK</button></div>';
$('m-c').onclick=async()=>{try{await navigator.clipboard.writeText(r.key);$('m-c').textContent=t.copied}catch(e){}};$('m-x').onclick=()=>{$('modal').classList.add('hide');load()}}};
$('q').oninput=()=>{q=$('q').value;paint()};$('rf').onclick=load;$('lo').onclick=()=>{session=null;D=null;try{sessionStorage.removeItem('loya_admin_s')}catch(e){}paint()};
async function doLogin(){const t=T();$('lerr').textContent='';const r=await api('admin-login',{password:$('pw').value});
if(r.ok){session=r.session;try{sessionStorage.setItem('loya_admin_s',session)}catch(e){}$('pw').value='';await load();return}
$('lerr').textContent=r.error==='admin_disabled'?t.off:r.error==='locked'?t.locked:r.error==='wrong'?t.wrong:t.err}
$('lb').onclick=doLogin;$('pw').onkeydown=e=>{if(e.key==='Enter')doLogin()};
paint();if(session)load();
</script></body></html>`;
module.exports = async (req, res) => {
  res.setHeader('Cache-Control', 'no-store'); res.setHeader('X-Robots-Tag', 'noindex, nofollow'); res.setHeader('Referrer-Policy', 'no-referrer');
  res.setHeader('Content-Type', 'text/html; charset=utf-8'); res.status(200).send(PAGE());
};
